Snapmaker/Luban

.travis.yml

- Format .travis YAML file
- Remove old unused keys
- Add new secure API key

Build: Update .travis.yml using new API key

---

src/app/widgets/Connection/SerialConnection.jsx
src/app/widgets/Connection/WifiConnection.jsx

Change the height to the maximum height

Fix: Fixed the bug that the port drag box is too long

---

.gitignore
package-lock.json

Reference:
https://medium.com/coinmonks/everything-you-wanted-to-know-about-package-lock-json-b81911aa8ab8

Build: Remove package-lock.json from .gitignore

---

.commitlintrc.js
CONTRIBUTING.md
README.md
package-lock.json
package.json

git-cz intercepts git rebase from use old commit message, and force user
to write new commit message. This is an unexpected behavior.
Use commitlint we can still use `npm run commit` to help write
conventional messages, and check the message with commitlint.

Docs: Add commitlint in replace of git-cz as githook

---

src/app/widgets/Macro/Macro.jsx
src/app/widgets/Macro/index.jsx
src/server/services/api/api-macros.js

This fix #265 and a quick fix for #267 
#267 needs further improvements but here we just fix it simple.

Fix: Solve the problem that marco has only a maximum of 10

---

src/app/constants/index.js
src/app/flux/machine/index.js

Solves the issue in https://forum.snapmaker.com/t/camera-capture-does-work-on-v3-3-3/5911

Fix: Fix the bug that click camera capture will cause the software to crash

---

.travis.yml
package-lock.json
package.json
src/package.json

Build: Increate macOS build time to 60 minutes 

---

src/app/containers/Settings/MachineSettings/MachineSettings.jsx
src/app/flux/printing/DefinitionManager.js
src/app/widgets/CNCOutput/Output.jsx
src/app/widgets/LaserOutput/Output.jsx
src/app/widgets/PrintingOutput/Output.jsx

- Fix the custom cannot modify x, y, z
- Fix 3dp generated gcode printing end z lifting speed is to slow
- Fix Laser/CNC can generate gcode when has no model

Fix: Fix bug for Snapmaker Luban 3.5.0

---

src/app/lib/threejs/ThreeDxfLoader.js
src/shared/lib/DXFParser/Parser.js

Fix DXF loader  Arc decode problem

Fix: Fix dxf arc's missing line

---

src/app/components/SMCanvas/Canvas.jsx
src/app/components/SMCanvas/Controls.jsx
src/app/widgets/CNCVisualizer/Visualizer.jsx
src/app/widgets/LaserVisualizer/Visualizer.jsx
src/app/widgets/PrintingVisualizer/Visualizer.jsx
src/app/widgets/WorkspaceVisualizer/Visualizer.jsx
src/app/workers/GcodeToBufferGeometry/GcodeToBufferGeometryWorkspace.js

- Fix: Fix bounding box calculation
- Improvement: Check model select on mouseup (click) event
- Improvement: Adjust camera position on new model loaded / machine size changed

Improvement set canvas camera position appropriate

---

src/app/constants/svg-constatns.js
src/app/flux/editor/base.js
src/app/flux/editor/index.js
src/app/flux/editor/svg-model.js
src/app/flux/editor/threejs-model.js
src/app/flux/models/ModelGroup.js
src/app/flux/models/SvgModelGroup.js
src/app/flux/printing/index.js
src/app/widgets/CNCVisualizer/Visualizer.jsx
src/app/widgets/CncLaserSvgEditor/SVGCanvas.jsx
src/app/widgets/CncLaserSvgEditor/element-utils.js
src/app/widgets/CncLaserSvgEditor/svg-content/SVGContentGroup.js
src/app/widgets/LaserVisualizer/Visualizer.jsx
src/server/lib/SVGParser/BaseTagParser.js
src/server/lib/SVGParser/SvgToString.js
src/server/lib/image-process.js
src/server/lib/svg-convert.js

- Add bring to front and send to back
- Fix bug that the 3dp model operation is error after duplicate
- Fix bug for flip
- Fix bug for Laser/CNC duplicate
- Fix bug that can`t generateGcode when unselect model

Fix: Fix bugs for 3.6.0

---

src/app/components/Modal/ModalSmallInput.jsx
src/app/i18n/de/resource.json
src/app/i18n/en/resource.json
src/app/widgets/Connection/WifiConnection.jsx
src/package.json

Based on https://github.com/Snapmaker/Luban/issues/350 I've added a very simple approach for manually connecting to a machine by IP.
This was done very naively by just allowing the user to input an IP and then call openServer. Do you think it might be an issue not having the "model" defined on the Server object?

Feature: Allow manual IP input for WiFi connection

---

src/app/widgets/Connection/LaserState.jsx
src/app/widgets/Connection/SerialConnection.jsx
src/app/widgets/Connection/WifiConnection.jsx

This is a follow improvement on #357 and #350 ,  changes as below:
- Add title to dropdown item in case text is too long
- "Connection" widget: Open -> Connect, Close -> Disconnect
- Correct display when no machine detected
- Correct float display of focal length

Improvement: Improve user experience when using manual Wi-Fi connection

---

src/app/flux/laser/index.js
src/app/flux/models/SvgModelGroup.js
src/app/widgets/CncLaserSvgEditor/SVGCanvas.jsx
src/app/widgets/CncLaserSvgEditor/svg-content/SVGContentGroup.js

Improvement: Increase SVG view translation

---

src/app/flux/models/Model.js
src/app/flux/models/ModelGroup.js
src/app/flux/models/SvgModel.js
src/app/flux/models/SvgModelGroup.js
src/app/widgets/CNCPath/CNCPath.jsx
src/app/widgets/CNCPath/gcodeconfig/ReliefGcodeParameters.jsx
src/app/widgets/CncLaserObjectList/ObjectListBox.jsx
src/app/widgets/CncLaserShared/TextParameters.jsx
src/app/widgets/CncLaserSvgEditor/svg-content/SelectorManager.js
src/app/widgets/CncLaserSvgEditor/text-actions.js
src/app/widgets/LaserParams/LaserParameters.jsx
src/app/widgets/PrintingConfigurations/Configurations.jsx

Fix: Fix bugs & remove console logs

---

src/app/lib/threejs/ThreeDxfLoader.js
src/app/widgets/PrintingConfigurations/Configurations.jsx
src/shared/lib/DXFParser/Parser.js
src/shared/lib/DXFParser/entities/lwpolyline.js

Fix: Fix LWPOLYLINE drawing when have bulge attributes
Refactor:  Refactor to expand accuracy when draw SPLINE

Fix: Fix two dxf accuracy bug

---

src/app/flux/editor/index.js
src/app/flux/models/Model.js
src/app/flux/models/ModelGroup.js
src/app/flux/models/SvgModel.js
src/app/flux/models/SvgModelGroup.js
src/app/flux/models/ToolPathModelGroup.js
src/app/widgets/CNCPath/CNCPath.jsx
src/app/widgets/CncLaserShared/Transformation.jsx
src/app/widgets/CncLaserSvgEditor/SVGCanvas.jsx
src/app/widgets/CncLaserSvgEditor/SVGEditor.jsx
src/app/widgets/CncLaserSvgEditor/text-actions.js
src/app/widgets/LaserParams/gcodeconfig/GcodeConfigRasterVector.jsx

- Fixed serveral bugs for SVG Editor

Fix: Fix bugs for SVG Editor

---

src/app/widgets/CncLaserShared/GcodeParameters.jsx

Fix dwell time unit display mentioned in https://github.com/Snapmaker/Luban/issues/424

Improvement: Fix dwell time unit for laser greyscale mode

---

.travis.yml
README.md
package.json

RPM builds as feature request by https://github.com/Snapmaker/Luban/issues/423

Build: Add support for RPM packages

---

package-lock.json
package.json
src/app/flux/models/Model.js
src/app/flux/project/index.js
src/app/lib/uni-api.js
src/electron-app/Menu.js
src/electron-app/window.js
src/main.js
src/server/services/api/api-file.js

Build: Upgrade electron from 2.0.y to 8.x.y

---

src/app/containers/App.jsx
src/app/flux/models/SvgModel.js
src/app/flux/project/index.js
src/app/lib/uni-api.js
src/electron-app/Menu.js

- Improvement: Be able to create new file
- Improvement: Sort recent files when open file

Improvement: Be able to create new file

---

src/app/components/SMCanvas/TransformControls.js
src/app/models/ModelGroup.js
src/app/widgets/PrintingVisualizer/VisualizerInfo.jsx

Feature: Show 3DP model size information in canvas

---

src/app/widgets/LaserParams/config/ConfigRasterVector.jsx

Replica of https://github.com/Snapmaker/Luban/pull/510

Fix: Correct Raster Vector slider and number maximum values to be equal

---

resources/CuraEngine/Config/snapmaker.def.json
src/app/flux/printing/DefinitionManager.js

- Set cura config support_wall_count on switching support_pattern

Improvement: Set cura config support_wall_count

---

package.json
src/app/api/index.js
src/app/flux/editor/index.js
src/app/models/SVGActionsFactory.js
src/app/models/SvgModel.js
src/app/widgets/LaserParams/LaserParameters.jsx
src/package.json
src/server/lib/FontManager.js
src/server/lib/svg-convert.js
src/server/services/api/api-svg.js
src/server/services/api/api-utils.js
src/server/services/index.js
src/server/services/task-manager/generateToolPath.js

- todo, toolpath position not at the same place

Improvement: Set laser text process mode to vector

---

src/app/flux/editor/index.js

Fix: Fix print order display bug on laser/cnc

---

package-lock.json
package.json
src/package.json
src/server/lib/parseGcodeHeader.js

Fix: Correct G-code header parsing forloop

---

src/main.js

Revert application window behavior as discussed in https://github.com/Snapmaker/Luban/issues/554

Improvement: Quit application when all windows closed

---

src/app/flux/editor/index.js
src/app/models/ModelInfoUtils.js
src/server/lib/MeshProcess/Polygons.js
src/server/lib/MeshProcess/Slicer.js
src/server/lib/ToolPath/index.js
src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js
test/cnc-mesh-slice/complexity-analysis/martinez-polygon-clipping/main.js
test/cnc-mesh-slice/main.js

- Optimize the time and memory usage of the cnc linkage slicing algorithm

Improvement: Add stew down for CncMeshLinkageToolPathGenerator

---

src/app/components/SMCanvas/TransformControls.js
src/app/components/three-extensions/ThreeUtils.js
src/app/models/Model.js
src/app/models/ModelGroup.js
src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js

Fix: Fix svg flip bug
Fix: Fix mesh material bug

Refactor: Refactor compute model bounding box

---

src/app/components/three-extensions/ThreeUtils.js
src/app/models/Model.js
src/app/models/ModelGroup.js
src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx

Fix: Fix threejs getWorldPosition warning
Fix: Fix support mode not disabled on multiselect

Fix: Fix computeBoundingBox bug for support mesh

---

src/app/flux/cnc/index.js
src/app/flux/editor/index.js
src/app/flux/laser/index.js
src/app/flux/machine/index.js
src/app/widgets/JobType/JobType.jsx

- Fix bug for job type display error

Fix: Fix bug for materials storage problem

---

src/app/models/ModelGroup.js

Fix: Fix Generate Gcode button status issue with supports

Fix: Fix Arrange All Model Action issue with supports

---

src/app/widgets/LaserParams/config/ConfigRasterVector.jsx

Fix: Fix invert option not working

---

src/app/components/SMCanvas/Controls.jsx
src/app/components/three-extensions/ThreeUtils.js
src/app/models/ModelGroup.js
src/app/widgets/CncLaserShared/Thumbnail.jsx
src/app/widgets/PrintingOutput/Thumbnail.jsx

- Fix: Fix model unselectable issue after support done
- Improvement: Support ToolpathModel for ThreeUtils.computeBoungingBox
- Fix: Fix thumbnail blancks by using ThreeUtil.computeBoundingBox

Fix: Fix thumbnail blanks by using ThreeUtil.computeBoundingBox

---

src/app/lib/normalize-range.js
src/app/ui/SVGEditor/SVGCanvas.jsx
src/app/views/CncToolManager/CncToolManager.jsx
src/app/views/PrintingManager/PrintingManager.jsx
src/app/widgets/CncLaserObjectList/ObjectListBox.jsx
src/app/widgets/PrintingObjectList/PrintingObjectListBox.jsx
src/main.js

* Fix: Fix the manager state will not change when retraction_hop_enabled parameter is changed
* Improvement: Add function to make the name in the manager not too long
* Fix: Fix saving the project file will not record the project file in the recent file

Fix: Fix bugs for parameter retraction_hop_enabled and recent project files

---

src/app/flux/editor/index.js
src/app/models/SVGActionsFactory.js
src/app/models/SvgModel.js
src/app/ui/SVGEditor/SVGCanvas.jsx
src/app/ui/SVGEditor/svg-content/OperatorPoints.js
src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
src/app/widgets/CNCPath/CNCPath.jsx
src/app/widgets/CncLaserShared/TransformationSection.jsx
src/app/widgets/LaserParams/LaserParameters.jsx

- fix "flip" option
- ellipse stroke width always = 1
- multi-select mouse handling
- multi-select position calculation
Reference: Internal JIRA LU-663

Fix: Fix several element operation bugs

---

src/app/containers/Cnc/styles.styl
src/app/containers/Laser/styles.styl

Fix: Change style for <Sortable> in laser | cnc

---

resources/CuraEngine/Config/cncConfig/Default.def.json
resources/CuraEngine/Config/cncConfig/active.def.json
src/app/components/SMCanvas/Controls.jsx
src/app/components/SMCanvas/TransformControls2D.js
src/app/constants/index.js
src/app/flux/cnc/index.js
src/app/flux/editor/actions-process.js
src/app/flux/editor/index.js
src/app/flux/keyboardShortcut/index.js
src/app/flux/laser/index.js
src/app/flux/widget/WidgetState.js
src/app/models/ModelGroup.js
src/app/models/ModelInfoUtils.js
src/app/toolpaths/ToolPath.js
src/app/toolpaths/ToolPathGroup.js
src/app/toolpaths/utils.js
src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
src/app/views/ToolPathConfigurations/ToolPathConfigurations.jsx
src/app/views/ToolPathConfigurations/cnc/CncParameters.jsx
src/app/views/ToolPathConfigurations/cnc/ToolParameters.jsx
src/app/views/ToolPathConfigurations/laser/LaserParameters.jsx
src/app/widgets/CNCPath/CNCPath.jsx
src/app/widgets/CNCVisualizer/Visualizer.jsx
src/app/widgets/CncLaserOutput/Output.jsx
src/app/widgets/LaserVisualizer/Visualizer.jsx

Bugs:
- Create toolpath component under laser shows exceptions
- Cnc toolpath part of the parameter details are missing
- No ctrl/command + a
- Configuring pop-up style issues
- The toolpath is regenerated after the configuration update

Fix: Fix bug for tool path

---

README.md
package.json

Preparations for arm64 build for Raspberry Pi

Build: Preparations for raspberry pi support

---

resources/CuraEngine/Config/snapmaker2.def.json
src/app/constants/index.js
src/app/flux/printing/index.js
src/server/slicer/definition.js

- Fix configuration file parse error
- Fix configuration not effective when open new file
- Change position of support_angle param

Fix: Fix 3dp printing configuration problems

---

src/app/flux/printing/index.js
src/app/models/ModelGroup.js
src/package.json

Fix: Fix missing dimension of 3DP models in G-code file

---

src/app/components/Input/NumberInput.jsx
src/app/flux/editor/index.js
src/app/models/SVGActionsFactory.js
src/app/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
src/app/views/Cnc3DVisualizer/Env3Axis.jsx
src/app/widgets/CNCVisualizer/Visualizer.jsx
src/app/widgets/CaseLibrary/CaseConfig.js

- Fix problem caused page blanks
- Fix model visualizer not show
- Fix scale not effect
- Fix progress bar problem
- Fix size shows 0 when inited
- Update job type when loading project from case library

Fix: Fix bugs for cnc

---

src/app/flux/editor/index.js
src/app/models/Model.js
src/app/models/ModelInfoUtils.js
src/server/lib/MeshProcess/Mesh.js
src/server/lib/MeshProcess/MeshProcess.js
src/server/services/api/api-image.js
src/server/services/task-manager/processImage.js

Reference Internal JIRA: SB-238

Fix: Fix the problem that STL in CNC editor is too large or too small

---

src/app/constants/index.js
src/app/models/ModelInfoUtils.js
src/app/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
src/app/widgets/CNCPath/Image3dParameters.jsx
src/server/constants/index.js
src/server/lib/MeshProcess/Mesh.js
src/server/lib/MeshProcess/MeshProcess.js
src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshToolPathGenerator.js

Reference Internal JIRA: SB-259

Improvement: Add 4-axis STL parameter "placement"

---

bin/cli
build/electron-builder.sh
build/prebuild-prod.sh
gulp/tasks/app.js
gulp/tasks/clean.js
gulp/tasks/server.js
package-lock.json
package.json
webpack.config.app.production.js
webpack.config.server.production.js

When using China CDN mirror to download electron, type as follows (To download 8.5.5 for example):
```Shell
export ELECTRON_MIRROR=https://npm.taobao.org/mirrors/electron/
export ELECTRON_CUSTOM_DIR=8.5.5
npm install electron
```
Reference:
- https://www.electronjs.org/docs/tutorial/installation#custom-mirrors-and-caches

Build: Update dependencies (electron mainly)

---

src/app/flux/editor/index.js
src/app/widgets/CNCVisualizer/Visualizer.jsx

Fix: Fix resize functions in cnc and fix synchronizeElements in flux/editor

---

package-lock.json
src/app/flux/editor/index.js
src/app/models/Model.js
src/app/models/ModelInfoUtils.js
src/app/models/SVGActionsFactory.js
src/app/models/SvgModel.js
src/app/widgets/PrintingOutput/Output.jsx
src/app/widgets/PrintingOutput/Thumbnail.jsx
src/shared/lib/DXFParser/DxfParser.js
src/shared/lib/utils.js

Fix: Fix scale of uploaded images

---

src/app/components/SMCanvas/Controls.jsx
src/app/lib/threejs/ThreeDxfLoader.js
src/server/lib/editor/dxf-process.js
src/shared/lib/DXFParser/Parser.js

Fix: Fix dxf storkewidth and dxf size when loading dxf on editor 
Fix: Fix can't select dxf model on process in laser/cnc part

Fix: Fix bug on dxf size and selection

---

src/app/lib/renderer/ViewPathRenderer.js
src/server/lib/ToolPathGenerator/CncToolPathGenerator.js
src/server/lib/bresenham-line.js

Reference Internal JIRA: SB-225

Fix: Fix svg simulation exception

---

src/app/styles/sm-parameter.styl
src/app/widgets/CncLaserShared/TextParameters.jsx
src/app/widgets/CncLaserShared/TransformationSection.jsx
src/app/widgets/CncLaserShared/styles.styl
src/package.json

Fix: Change style in Editor secondary bar

---

src/app/components/SMCanvas/Canvas.jsx
src/app/flux/editor/index.js
src/app/flux/printing/index.js
src/app/flux/project/index.js
src/app/lib/uni-api.js
src/app/models/Model.js
src/app/widgets/GCode/GCode.jsx
src/app/widgets/PrintingVisualizer/Visualizer.jsx
src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
src/app/widgets/WifiTransport/WifiTransport.jsx
src/server/services/api/api-file.js

Set proper camera position of Canvas.toFront when machine changed
Fix duplicate action in laser/cnc
Show days of elapsed time
Disable model actions of context menu when support being selected
Do not remove special chars of backend files
Fix SVG Flip not effected on toolpath in laser & cnc
Clear toolpath when opening new file
Set Save-As dialog as modal of current window
Fix supports disapear when doing undo
Disable rotate when multi-selecting supports
Fix gcode file name overflow problem

Fix: Fix bugs for v3.15

---

src/server/lib/clipper/cLipper-adapter.js

Do not need to merge to master

Fix: Modify the accuracy of the clipper

---

src/app/flux/editor/index.js
src/app/models/Model.js
src/app/models/SvgModel.js
src/app/ui/SVGEditor/SVGCanvas.jsx

SB-256
Change the material of modelObject3D to change background color of svg model in process.
Fix svg resize error.
Fix svg flip error.

Fix: Fix several SVG transformation synchronization bugs

---

resources/CuraEngine/Config/snapmaker.def.json
src/app/components/SMCanvas/Canvas.jsx
src/app/components/SMCanvas/Controls.jsx
src/app/lib/threejs/ThreeDxfLoader.js
src/app/widgets/CNCPath/gcodeconfig/Image3DGcodeParameters.jsx
src/shared/lib/DXFParser/Parser.js

Fix: Fix bug on dxf size and selection
Fix: Fix text related support for original machine and toolpath selection

Fix: Fix bugs on v3.14.0

---

src/app/flux/machine/index.js
src/app/widgets/Enclosure/Enclosure.jsx
src/app/widgets/Enclosure/EnclosureDisplay.jsx
src/app/widgets/Purifier/Purifier.jsx
src/app/widgets/Purifier/index.jsx

SB-273: Fix M1011 request error when machine is not support
SB-298: Fix warning in enclosure and purifier widgets, they will not appear when not connected.

Fix: Fix the widgets warning in enclosure and purifier

---

test/cnc-mesh-slice/complexity-analysis/martinez-polygon-clipping/main.js

Fix: Fix the bug that the test file references the deleted lib

---

src/app/flux/editor/index.js
src/app/models/SVGActionsFactory.js
src/app/models/SvgModel.js
src/app/ui/SVGEditor/SVGCanvas.jsx
src/app/ui/SVGEditor/SVGEditor.jsx
src/app/widgets/CNCVisualizer/Visualizer.jsx
src/app/widgets/CncLaserShared/TransformationSection.jsx
src/app/widgets/LaserVisualizer/Visualizer.jsx

Fix: Fix SVG uniform scale and enlarge text size

---

src/app/containers/App.jsx
src/app/flux/project/index.js
src/app/lib/uni-api.js
src/main.js

Fix: Disable automatic recovery when double-clicking the project file to
start the software (#774)

Fix: Disable automatic recovery when double-clicking the project file to start the software (#774)

---

src/app/widgets/CNCTool/styles.styl

Fixes SB-318
Don't pick to master!

Refactor: Change style on cnc tool

---

src/server/lib/MeshProcess/MeshProcess.js

Fix: Fix the suffix capital parsing bug of CNC STL file

---

src/app/models/SVGActionsFactory.js

Fix: Add onUpdate method after resize in transformation widget 

---

src/app/widgets/Marlin/Laser.jsx

Fix: Fix the value of some parameters in laser state has too many decimal places

---

src/app/flux/editor/index.js
src/app/widgets/CaseLibrary/CaseConfig.js

Improvement: Make the image size generated by STL less than or equal to the diameter

---

src/app/containers/App.jsx
src/app/containers/Sidebar/styles.styl
src/app/flux/laser/index.js
src/app/flux/machine/index.js
src/app/widgets/Console/Console.jsx
src/app/widgets/Console/Terminal.jsx
src/app/widgets/JobType/JobType.jsx
src/app/widgets/JobType/styles.styl
src/app/widgets/PrintingOutput/Output.jsx

Fixes SB-68 SB-299
Fixes SB-318 and  SB-70 
Need to be picked to master.

Fix: Fix fit-addon loading when the parent component is not loaded in Console widget

---

src/app/models/SVGActionsFactory.js
src/app/models/SvgModel.js

Fix: Set proper source size of model
Fix: Remove extra transform in svg element's transformlist

Fix: Fix bugs for v3.14

---

src/app/flux/editor/index.js

Fix: Fix cnc stl 3 axis loading bugs

---

src/app/widgets/CncLaserOutput/Output.jsx

Fix: Fix the bug that the button 'preview tool path' cannot be clicked

---

src/app/styles/sm-parameter.styl
src/app/widgets/CncLaserShared/Transformation.jsx
src/app/widgets/CncLaserShared/styles.styl
src/app/widgets/JobType/styles.styl

SB-314.
Improve the style of Laser|CNC transformation.
Cherry pick master pls. About SB-257.

Improvement: Change style in transformation of laser and cnc

---

src/app/components/SMCanvas/Canvas.jsx
src/app/components/SMCanvas/Controls.jsx
src/app/flux/machine/index.js
src/app/widgets/Control/Control.jsx
src/app/widgets/Control/DisplayPanel.jsx
src/app/widgets/Control/JogDistance.jsx
src/app/widgets/Control/index.styl
src/app/widgets/GCode/GCode.jsx
src/app/widgets/LaserCameraAidBackground/SetBackground.jsx
src/app/widgets/Marlin/Laser.jsx
src/server/services/api/api-file.js

* Fix: Fix editor operation occasionally causes Block
* Fix: Fix meshobject cannot be selected after the canvas rotates 180 degrees around the Y axis in cnc/laser tab
* Improvement: Hide capture button when machine is four axis
* Fix: Fix bugs related to four axis

 Fix: Fix bugs on v3.14

---

src/app/containers/Header/MachineSelection.jsx

Fix: Add isConnected flag to control machine size setting button

---

src/server/lib/MeshProcess/MeshProcess.js
src/server/lib/MeshProcess/Polygons.js
src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshToolPathGenerator.js
src/server/services/task-manager/generateToolPath.js
src/server/services/task-manager/generateViewPath.js

JIRA: SB-381 SB-361
- Z minimum is zero in CNC STL rotation mode slice
- Fix the accuracy loss caused by STL to image conversion

Improvement: Increase the distance between the vertices allowed by the polygon

---

src/app/flux/setting/index.js

Fix: Load 3DP case model error after reset config

---

src/server/lib/ToolPath/XToBToolPath.js
src/server/lib/ToolPath/index.js
src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
src/server/lib/ToolPathGenerator/CncToolPathGenerator.js
src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js

Improvement: Reset to zero at the end of 4-axis printing b

---

src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshToolPathGenerator.js

 Fix: Fix the size bug of stl 3-axis ball knife

---

src/app/models/Model.js

Change the material of modelObject3D to change background color of svg model in process.
1st question of https://github.com/Snapmaker/Luban/pull/784 for master

Fix: Change the material of modelObject3D

---

src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js

Fix: Fix CNC STL slice interpolation bug

---

src/electron-app/Menu.js

Fix: Remove application edit menu temporarily

---

src/server/lib/ToolPathGenerator/MeshToolPath/CncMeshLinkageToolPathGenerator.js

Fix: Fix bug for CNC STL linkage bounding box

---

src/app/flux/editor/index.js

Improvement: Recalculate STL model size

---

src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js

Fix: Fix bug for CNC relief rotation bug

---

src/app/flux/printing/index.js

Fix: Fix bug for 3D printing bounding box

---

src/app/widgets/CncLaserShared/TransformationSection.jsx

Fix: Fix transformation style error after pick from 3.14

---

src/server/controllers/Marlin/Marlin.js

Fix: Hide B axis log in console when connected by serial port 3.15

---

src/app/models/ModelGroup.js

Fix: Fix reset transformation error when multiselected

---

resources/CuraEngine/Config/CncConfig/Default.def.json
resources/CuraEngine/Config/CncConfig/active.def.json

Fix: Fix description error in cnc tool path

---

src/app/components/SMCanvas/Canvas.jsx
src/app/containers/App.jsx
src/app/flux/project/index.js
src/app/lib/modal.jsx
src/app/models/ModelGroup.js
src/app/models/ThreeModel.js
src/app/ui/SVGEditor/SVGCanvas.jsx
src/app/ui/SVGEditor/TextActions.js

Fix SVG text input problem
Fix 3dp undo problem with supports

Improvement: Show modal before recovering environment

---

src/app/widgets/CNCPath/CNCPath.jsx

Fix: Switch description of work speed and plunge speed for 3.14

---

src/app/lib/time-utils.js
src/app/widgets/CNCVisualizer/Visualizer.jsx
src/app/widgets/LaserVisualizer/Visualizer.jsx
src/app/widgets/PrintingVisualizer/VisualizerInfo.jsx
src/shared/lib/SVGParser/AttributesParser.js

Seems like estimated printing time of Laser and CNC are broken. Should be fixed soon.
Fixes #898

Fix: Fix false calculation of ETA 3D printing time

---

src/app/models/BaseModel.js
src/app/models/ModelGroup.js
src/app/models/SVGActionsFactory.js
src/app/models/SvgModel.js
src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
src/app/widgets/CaseLibrary/CaseConfig.js
src/app/widgets/Webcam/index.jsx
src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js
src/server/lib/editor/image-process.js

Refactor: Remove variable "flip"

---

src/app/lib/renderer/ToolPathRenderer.js
src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js

Feature: Add dot movement mode for laser bw and halftone

---

src/app/widgets/JobType/JobType.jsx

[SB-448](https://snapmaker2.atlassian.net/browse/SB-448)

Fix: Fix right control bar twitch in laser and cnc

---

src/app/widgets/PrintingConfigurations/Configurations.jsx
src/app/widgets/PrintingConfigurations/styles.styl
src/app/widgets/PrintingMaterial/Material.jsx

[LU-715](https://snapmaker2.atlassian.net/browse/LU-715)

Refactor: Add 2 variables in 3D printing settings details

---

src/app/constants/index.js
src/app/models/SvgModel.js
src/app/widgets/CncLaserShared/TransformationSection.jsx
src/server/lib/svg-convert.js

[SB-454](https://snapmaker2.atlassian.net/browse/SB-454)

Fix: Fix process image err on un-uniform scaling of SVG Text

---

src/app/widgets/CaseLibrary/CaseConfig.js

Fix: Change case library definitionId to digital serial to fit project

---

resources/CuraEngine/Config/material.abs.def.json
resources/CuraEngine/Config/material.pla.def.json
src/app/containers/App.jsx
src/app/flux/printing/index.js
src/app/lib/modal.jsx
src/app/views/ToolPathConfigurations/ToolPathConfigurations.jsx
src/app/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
src/app/widgets/CncLaserTopRight/VisualizerTopRight.jsx
src/app/widgets/PrintingConfigurations/Configurations.jsx
src/app/widgets/PrintingMaterial/Material.jsx

Supply LU-714  SB-486
And some other bug

Fix: Fix process bug in laser and cnc

---

src/app/widgets/Enclosure/Enclosure.jsx

[SB-437](https://snapmaker2.atlassian.net/browse/SB-437)

Fix: Fix door detection error in workspace

---

src/app/containers/App.jsx
src/app/i18n/cs/resource.json
src/app/i18n/de/resource.json
src/app/i18n/en/resource.json
src/app/i18n/es/resource.json
src/app/i18n/fr/resource.json
src/app/i18n/hu/resource.json
src/app/i18n/it/resource.json
src/app/i18n/ja/resource.json
src/app/i18n/ko/resource.json
src/app/i18n/pt-br/resource.json
src/app/i18n/ru/resource.json
src/app/i18n/uk/resource.json
src/app/i18n/zh-cn/resource.json
src/app/i18n/zh-tw/resource.json
src/app/toolpaths/utils.js
src/app/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
src/app/widgets/CncLaserShared/TransformationSection.jsx
src/app/widgets/PrintingConfigurations/Configurations.jsx
src/app/widgets/PrintingMaterial/Material.jsx

[SB-490](https://snapmaker2.atlassian.net/browse/SB-490) [SB-506](https://snapmaker2.atlassian.net/browse/SB-506)

Refactor: Change styles and i18n words

---

src/app/flux/project/index.js
src/app/widgets/Enclosure/Enclosure.jsx

Pick [SB-188](https://snapmaker2.atlassian.net/browse/SB-188) [SB-437](https://snapmaker2.atlassian.net/browse/SB-437) to 3.14

Fix: Fix door detection error and new file error in 3.14

---

resources/CuraEngine/Config/snapmaker.def.json
src/app/models/SVGActionsFactory.js

Update Model on setting Reference Position
Hide 3dp param 'material_diameter'

Fix: Fix bugs for 3.15-alpha.28

---

src/app/flux/cnc/index.js
src/app/flux/editor/actions-process.js
src/app/widgets/CncLaserTopRight/VisualizerTopRight.jsx

[SB-502](https://snapmaker2.atlassian.net/browse/SB-502)

Improvement: Add simulation need to preview flag in cnc state

---

src/app/flux/editor/index.js
src/app/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx

Fix: Fix cnc stl 3d view size bug

---

src/app/constants/index.js
src/app/containers/Cnc/Cnc.jsx
src/app/models/ModelInfoUtils.js
src/app/toolpaths/utils.js
src/app/widgets/CNCVisualizer/VisualizerTopLeft.jsx
src/server/constants/index.js
src/server/services/task-manager/generateToolPath.js
src/server/services/task-manager/generateViewPath.js

Fix: Fix the parameter bug in svg black and white mode

---

src/server/controllers/Marlin/Marlin.js

[LU-817](https://snapmaker2.atlassian.net/browse/LU-817)

Fix: Catch M1011 not found error 

---

src/app/components/SMCanvas/Canvas.jsx
src/app/constants/index.js
src/app/flux/cnc/index.js
src/app/flux/editor/index.js
src/app/flux/laser/index.js
src/app/flux/project/index.js
src/app/models/ModelGroup.js
src/app/models/SVGActionsFactory.js
src/app/ui/SVGEditor/PrintableArea.js
src/app/ui/SVGEditor/SVGCanvas.jsx
src/app/ui/SVGEditor/SVGEditor.jsx
src/app/widgets/CNCVisualizer/Visualizer.jsx
src/app/widgets/CncLaserShared/PrintablePlate/CoordinateAxes.js
src/app/widgets/CncLaserShared/PrintablePlate/GridLine.js
src/app/widgets/CncLaserShared/PrintablePlate/PrintablePlate.jsx
src/app/widgets/JobType/JobType.jsx
src/app/widgets/LaserVisualizer/Visualizer.jsx
src/app/widgets/WorkspaceVisualizer/Visualizer.jsx

[LU-779](https://snapmaker2.atlassian.net/browse/LU-779)

Improvement: Add canvas size setting in job type

---

src/app/flux/widget/WidgetState.js
src/app/ui/Pages/Workspace.jsx
src/app/ui/utils/renderWidgetList.jsx
src/app/ui/widgets/MachineSetting/index.jsx
src/app/ui/widgets/MachineSetting/machineSetting.jsx
src/app/ui/widgets/MachineSetting/styles.styl
src/app/ui/widgets/Widget.jsx

Feature: Add machine setting in workspace left bar

---

src/app/ui/Layouts/HomeLayout.jsx
src/app/ui/Layouts/MenuItem.jsx
src/app/ui/Pages/Cnc.jsx
src/app/ui/Pages/HomePage/index.jsx
src/app/ui/Pages/Laser.jsx
src/app/ui/Pages/Printing.jsx
src/app/ui/Pages/Workspace.jsx
src/app/ui/components/SvgIcon/SvgIcon.jsx
src/app/ui/widgets/CncLaserOutput/Output.jsx
src/app/ui/widgets/JobType/JobType.jsx
src/app/ui/widgets/PrintingOutput/Output.jsx

Improvement: Improve main tool bar

---

src/app/constants/index.js
src/app/flux/appbar-menu/index.js
src/app/flux/editor/actions-process.js
src/app/flux/editor/index.js
src/app/flux/project/index.js
src/app/toolpaths/ToolPathGroup.js
src/app/ui/pages/Cnc.jsx
src/app/ui/pages/HomePage/Begin.jsx
src/app/ui/pages/Laser.jsx
src/app/ui/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
src/app/ui/views/ToolPathConfigurations/cnc/CncParameters.jsx
src/app/ui/views/ToolPathConfigurations/cnc/ToolSelector.jsx
src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
src/app/ui/widgets/CncLaserList/styles.styl
src/app/ui/widgets/PrintingObjectList/styles.styl
src/server/controllers/Marlin/Marlin.js

[LU-931](https://snapmaker2.atlassian.net/browse/LU-931 )
[LU-1082](https://snapmaker2.atlassian.net/browse/LU-1082 )
Refactor PR 1046: remove consoles and rename fastEdit and toolSelector.
Fix [LU-829](https://snapmaker2.atlassian.net/browse/LU-829)

Fix: Fix saving project error and coordinate mode error

---

src/app/flux/appbar-menu/index.js
src/app/flux/printing/index.js
src/app/lib/normalize-range.js
src/app/ui/SVGEditor/SVGCanvas.jsx
src/app/ui/components/SMCanvas/Controls.jsx
src/app/ui/layouts/AppLayout.jsx
src/app/ui/utils/renderRecoveryModal.jsx
src/app/ui/views/AppBar/AppBar.jsx
src/app/ui/views/model-item.jsx
src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
src/app/ui/widgets/CncLaserList/styles.styl
src/app/ui/widgets/JobType/JobType.jsx
src/app/ui/widgets/PrintingObjectList/styles.styl
src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx
src/shared/lib/gcodeToolPath.js

[LU-895](https://snapmaker2.atlassian.net/browse/LU-895)
[LU-890](https://snapmaker2.atlassian.net/browse/LU-890)
[LU-879](https://snapmaker2.atlassian.net/browse/LU-879)
[LU-963](https://snapmaker2.atlassian.net/browse/LU-963)
[LU-897](https://snapmaker2.atlassian.net/browse/LU-897)

Fix: Fix v3.15 left issues

---

src/app/flux/project/index.js
src/app/lib/numeric-utils.js
src/app/ui/pages/Laser.jsx
src/app/ui/widgets/CncLaserOutput/Output.jsx

[LU-1087](https://snapmaker2.atlassian.net/browse/LU-1087)
issue NO.25
issue NO.27
issue NO.10
issue NO.1

Fix: bugfix alpha-2

---

src/app/styles/global-edge-distance.styl
src/app/styles/global-layout.styl
src/app/styles/global-var.styl
src/app/ui/pages/Cnc.jsx
src/app/ui/pages/Laser.jsx
src/app/ui/views/ProfileManager/ConfigValueBox.jsx
src/app/ui/views/ProfileManager/SettingItem.jsx
src/app/ui/views/ProfileManager/index.jsx
src/app/ui/views/ToolPathConfigurations/cnc/CncParameters.jsx
src/app/ui/views/ToolPathConfigurations/cnc/GcodeParameters.jsx
src/app/ui/views/ToolPathConfigurations/cnc/ToolParameters.jsx
src/app/ui/views/ToolPathConfigurations/cnc/ToolSelector.jsx
src/app/ui/views/ToolPathConfigurations/laser/GcodeParameters.jsx
src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
src/app/ui/widgets/CNCPath/Image3dParameters.jsx
src/app/ui/widgets/CNCPath/ImageProcessMode.jsx
src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
src/app/ui/widgets/CncLaserList/styles.styl
src/app/ui/widgets/PrintingConfigurations/Configurations.jsx
src/server/DataStorage.js

Refactor: UI change, profile manager, toolPath list box, toolPath edit(laser, cnc)
Fix: Fix reset value error after restart luban

Fix: Fix profile manager reset error after restart Luban

---

src/app/styles/global-background.styl
src/app/styles/global-edge-distance.styl
src/app/styles/global-layout.styl
src/app/styles/global-var.styl
src/app/ui/views/model-item.jsx
src/app/ui/widgets/CNCPath/ImageProcessMode.jsx
src/app/ui/widgets/PrintingObjectList/PrintingObjectListBox.jsx
src/app/ui/widgets/PrintingObjectList/styles.styl
src/app/ui/widgets/PrintingVisualizer/VisualizerBottomLeft.jsx
src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
src/app/ui/widgets/PrintingVisualizer/styles.styl

Change 3DP bottom left style
Change 3DP left bar style

Refactor: Change 3dp UI

---

package.json

Fix: Luban Engine compatible with Mac OS 10.13

Fix: Fix bug for luban engine

---

src/app/toolpaths/ToolPath.js
src/server/services/task-manager/TaskManager.js
src/server/services/task-manager/generateToolPath.js
src/server/slicer/call-engine.js

Feature: Change Laser/CNC toolpath generation to concurrent

Feature: Change Laser/CNC toolpath generation to concurrent

---

src/app/config/menu/editMenu.js
src/app/config/menu/fileMenu.js
src/app/flux/appbar-menu/index.js
src/app/flux/editor/index.js
src/app/flux/printing/index.js
src/app/lib/shortcut/constants.js
src/app/lib/shortcut/manager.js
src/app/lib/uni-api.js
src/app/models/ModelGroup.js
src/app/models/SVGActionsFactory.js
src/app/models/SvgModel.js
src/app/ui/App.jsx
src/app/ui/SVGEditor/SVGEditor.jsx
src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
src/app/ui/components/Modal/tileModal.jsx
src/app/ui/layouts/AppLayout.jsx
src/app/ui/views/AppBar/AppBar.jsx
src/app/ui/views/model-item.jsx
src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
src/app/ui/widgets/CncLaserList/ObjectList/ObjectListBox.jsx
src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
src/app/ui/widgets/PrintingObjectList/PrintingObjectListBox.jsx
src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx

[LU-1196](https://snapmaker2.atlassian.net/browse/LU-1196)

Feature: Add shortcuts in 3dp & laser & cnc & appbar

---

src/app/flux/editor/index.js
src/app/flux/operation-history/MoveOperation3D.js
src/app/flux/operation-history/ScaleOperation3D.js
src/app/flux/printing/index.js
src/app/models/ModelGroup.js
src/app/ui/components/SvgIcon/SvgIcon.jsx
src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx

[LU-1179](https://snapmaker2.atlassian.net/browse/LU-1179)
[LU-1222](https://snapmaker2.atlassian.net/browse/LU-1222)

Feature: Undo & redo support scaling and moving

---

src/app/constants/index.js
src/app/flux/printing/DefinitionManager.js
src/app/flux/project/index.js
src/app/ui/pages/HomePage/index.jsx

Fix Original Long Z-axis config error

Fix: Show recovery popup only on homepage

---

src/app/flux/cnc/index.js
src/app/flux/editor/actions-process.js
src/app/flux/editor/index.js
src/app/flux/laser/index.js
src/app/toolpaths/ToolPathGroup.js
src/app/ui/SVGEditor/PrintableArea.js
src/app/ui/widgets/CncLaserOutput/Output.jsx
src/app/ui/widgets/CncLaserShared/PrintablePlate/GridLine.js
src/app/ui/widgets/CncLaserShared/PrintablePlate/PrintablePlate.jsx
src/app/ui/widgets/JobType/JobType.jsx
src/app/ui/widgets/LaserSetBackground/ExtractSquareTrace/index.jsx

Fix: Fix laser cnc error

---

src/app/lib/uni-api.js

[LU-1301](https://snapmaker2.atlassian.net/browse/LU-1301) issue 6

Fix: Open file in workspace filter project extensions

---

src/app/flux/editor/actions-process.js
src/app/flux/editor/index.js
src/app/flux/printing/index.js
src/app/lib/controller.js
src/app/toolpaths/ToolPathGroup.js
src/app/ui/pages/Cnc.jsx
src/app/ui/pages/Laser.jsx
src/app/ui/widgets/CncLaserOutput/Output.jsx
src/app/ui/widgets/PrintingMaterial/Material.jsx
src/server/lib/ToolPathGenerator/CncReliefToolPathGenerator.js

https://snapmaker2.atlassian.net/browse/LU-1251
https://snapmaker2.atlassian.net/browse/LU-1293
https://snapmaker2.atlassian.net/browse/LU-1142
https://snapmaker2.atlassian.net/browse/LU-1238
https://snapmaker2.atlassian.net/browse/LU-1095
https://snapmaker2.atlassian.net/browse/LU-1135
https://snapmaker2.atlassian.net/browse/LU-1298
https://snapmaker2.atlassian.net/browse/LU-1294

Fix: Not to return model view after undo redo

---

src/app/ui/pages/HomePage/Begin.jsx
src/app/ui/pages/HomePage/styles.styl

[LU-1291](https://snapmaker2.atlassian.net/browse/LU-1291)

Fix: Home page laser&cnc button click inaccurate

---

src/app/flux/editor/actions-process.js
src/app/flux/printing/index.js
src/app/flux/project/index.js
src/app/models/ThreeModel.js
src/app/ui/widgets/CncLaserOutput/Output.jsx
src/app/ui/widgets/PrintingOutput/Output.jsx
src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx

[LU-1288](https://snapmaker2.atlassian.net/browse/LU-1288) issue 2 and 6
[LU-1239](https://snapmaker2.atlassian.net/browse/LU-1239)

Fix: Fix alpha4 bugfix

---

src/app/lib/redux-middleware.js
src/app/lib/uni-api.js
src/app/ui/layouts/AppLayout.jsx
src/app/ui/pages/HomePage/Begin.jsx
src/electron-app/Menu.js

[LU-1314](https://snapmaker2.atlassian.net/browse/LU-1314)

Fix: New file from appbar menu incorrect

---

src/app/flux/cnc/index.js
src/app/flux/editor/index.js
src/app/flux/laser/index.js
src/app/flux/printing/index.js
src/app/lib/controller.js
src/app/three-extensions/STLExporter.js
src/app/ui/SVGEditor/SVGCanvas.jsx
src/app/ui/pages/Laser.jsx
src/app/ui/widgets/CNCPath/CNCPath.jsx
src/app/ui/widgets/CNCPath/ImageProcessMode.jsx
src/app/ui/widgets/LaserParams/ImageProcessMode.jsx
src/app/ui/widgets/LaserParams/LaserParameters.jsx
src/app/ui/widgets/LaserVisualizer/Visualizer.jsx

Fix: LU-1328 LU-1337 LU-1159 LU-1315 LU-1312 LU-1245 LU-1339
Improvement: [LU-1285](https://snapmaker2.atlassian.net/browse/LU-1285)

Fix: Fix some laser|cnc canvas error and serial port connection error

---

package.json
src/app/flux/editor/actions-process.js
src/app/flux/workspace/index.js
src/app/toolpaths/ToolPath.js
src/app/toolpaths/ToolPathGroup.js
src/app/ui/views/Cnc3DVisualizer/Cnc3DVisualizer.jsx
src/app/ui/widgets/CncLaserOutput/Output.jsx
src/server/services/api/api-file.js
src/server/services/api/api-image.js
src/server/slicer/slice.js
src/shared/lib/random-utils.js

- Fix the bug of Chinese file name and some symbols 
- Fix bug for laser/cnc thumbnail
- Add CNC STL rotation support

Improvement: Update snapmaker-luban-engine to 0.4.0

---

src/app/flux/cnc/index.js
src/app/flux/editor/actions-process.js
src/app/flux/editor/index.js
src/app/flux/laser/index.js
src/app/flux/project/index.js
src/app/toolpaths/ToolPath.js
src/app/toolpaths/ToolPathGroup.js
src/app/ui/SVGEditor/SVGCanvas.jsx
src/app/ui/SVGEditor/index.styl
src/app/ui/pages/Cnc.jsx
src/app/ui/pages/Laser.jsx
src/app/ui/views/CncToolManager/CncToolManager.jsx
src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
src/app/ui/views/ToolPathConfigurations/ToolPathFastConfigurations.jsx
src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
src/app/ui/widgets/CncLaserOutput/Output.jsx
src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
src/shared/lib/SVGParser/AttributesParser.js

[LU-1335](https://snapmaker2.atlassian.net/browse/LU-1335) issues 1284, 1198, 1303

Fix: Toolpath update in preview mode

---

package.json
src/server/lib/editor/image-process.js

- Fix 16 bit PNG image processing exception
- Fix single channel picture exception
- Improvement: Replace the regex of C++ STL with the regex of boost
- Fix bug for image invert
- Fix image halftone

Feature: Update Luban Engine to 0.4.2

---

src/app/ui/widgets/PrintingMaterial/Material.jsx

Cause default heated bed temperature error.

Fix: Set material settings default value

---

src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx

Fix: Fix 3dp non-uniformscale error in left bar

---

src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx

Fix: Fix cnc tool path config error

---

src/app/flux/cnc/index.js
src/app/flux/editor/index.js
src/app/flux/laser/index.js
src/app/flux/printing/index.js
src/app/lib/hooks/previous.jsx
src/app/ui/components/Modal/modalBody.jsx
src/app/ui/layouts/WorkspaceLayout.jsx
src/app/ui/pages/Cnc.jsx
src/app/ui/pages/Laser.jsx
src/app/ui/pages/Workspace.jsx
src/app/ui/widgets/Connection/Connection.jsx
src/app/ui/widgets/Connection/SerialConnection.jsx
src/app/ui/widgets/Connection/WifiConnection.jsx
src/app/ui/widgets/Console/Console.jsx
src/app/ui/widgets/Console/Terminal.jsx
src/app/ui/widgets/Control/Control.jsx
src/app/ui/widgets/Enclosure/Enclosure.jsx
src/app/ui/widgets/Enclosure/EnclosureDisplay.jsx
src/app/ui/widgets/GCode/GCode.jsx
src/app/ui/widgets/JobType/JobType.jsx
src/app/ui/widgets/Macro/Macro.jsx
src/app/ui/widgets/Macro/index.jsx
src/app/ui/widgets/Marlin/Marlin.jsx
src/app/ui/widgets/Purifier/Purifier.jsx
src/app/ui/widgets/WifiTransport/WifiTransport.jsx
src/app/ui/widgets/WifiTransport/index.styl
src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx

[LU-1479](https://snapmaker2.atlassian.net/browse/LU-1479)

Refactor: Refactor workspace hooks

---

src/app/flux/printing/index.js
src/app/lib/manager/ProgressManager.js
src/app/models/ModelGroup.js
src/app/models/ThreeModel.js
src/app/three-extensions/ThreeUtils.js
src/app/ui/App.jsx
src/app/ui/components/SMCanvas/Canvas.jsx
src/app/ui/components/SMCanvas/Controls.jsx
src/app/ui/components/SMCanvas/TransformControls.js
src/app/ui/pages/Printing.jsx
src/app/ui/views/model-item.jsx
src/app/ui/widgets/PrintingObjectList/PrintingObjectListBox.jsx
src/app/ui/widgets/PrintingOutput/Output.jsx
src/app/ui/widgets/PrintingVisualizer/Overlay/RotationAnalysisOverlay.jsx
src/app/ui/widgets/PrintingVisualizer/Overlay/styles.styl
src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx

[LU-1470](https://snapmaker2.atlassian.net/browse/LU-1470)

Feature: 3DP manual placement

---

src/app/models/ModelGroup.js
src/app/ui/layouts/AppLayout.jsx

Fix: Fix change 3|4 axis error

---

src/app/ui/views/ToolPathConfigurations/ToolPathFastConfigurations.jsx
src/app/ui/views/ToolPathConfigurations/laser/LaserParameters.jsx
src/package.json

Fix: Fix laser multi pass param error in fill method

---

src/app/models/ModelGroup.js
src/app/ui/components/SMCanvas/Controls.jsx
src/app/ui/components/SMCanvas/TransformControls.js
src/app/ui/widgets/PrintingVisualizer/Overlay/RotationAnalysisOverlay.jsx

[LU-1551](https://snapmaker2.atlassian.net/browse/LU-1551) issue 1-c

Fix: Same position trigger click & UI improvement

---

package.json
src/app/flux/editor/index.js
src/app/lib/numeral.js
src/package.json

[LU-1525](https://snapmaker2.atlassian.net/browse/LU-1525)

Fix: Bugfix v4.0 png process

---

src/app/models/ThreeModel.js

[LU-1383](https://snapmaker2.atlassian.net/browse/LU-1383)

Fix: Fix generate code disabled after rotation

---

src/app/flux/cnc/index.js
src/app/flux/editor/index.js
src/app/flux/laser/index.js
src/app/flux/operation-history/ScaleOperation2D.js
src/app/flux/project/index.js
src/app/models/ModelGroup.js
src/app/models/SVGActionsFactory.js
src/app/models/SvgModel.js
src/app/models/ThreeModel.js
src/app/ui/widgets/CNCPath/CNCPath.jsx
src/app/ui/widgets/CNCPath/ImageProcessMode.jsx
src/app/ui/widgets/CncLaserShared/TransformationSection.jsx
src/app/ui/widgets/LaserParams/ImageProcessMode.jsx
src/server/lib/svg-convert.js
src/shared/lib/DXFParser/Parser.js
src/shared/lib/SVGParser/Parser.js
src/shared/lib/SVGParser/SvgToString.js

[LU-1522](https://snapmaker2.atlassian.net/browse/LU-1522)

Feature: Image non-uniform scaling

---

src/app/flux/editor/actions-process.js

Fix: Fix generating toolpath error

---

src/app/flux/editor/index.js
src/app/ui/widgets/JobType/JobType.jsx

Fix: Fix job setting error

---

src/app/ui/widgets/LaserSetBackground/PrintSquareTrace/index.jsx
src/app/ui/widgets/WifiTransport/WifiTransport.jsx

Fix: Fix original laser print square trace

---

src/app/ui/widgets/LaserStackedModel/Canvas/index.jsx
src/app/ui/widgets/LaserStackedModel/Canvas/styles.styl
src/app/ui/widgets/LaserStackedModel/index.jsx
src/app/ui/widgets/LaserStackedModel/styles.styl

[LU-1711](https://snapmaker2.atlassian.net/browse/LU-1711)

Improvement: Update model cut UI & decrease CPU usage

---

src/app/api/index.js
src/app/flux/setting/index.js
src/app/lib/i18n.js
src/app/ui/App.jsx
src/server/DataStorage.js
src/server/services/api/api-users.js
src/server/services/index.js

[LU-1718](https://snapmaker2.atlassian.net/browse/LU-1718)

Feature: Add shortcut for reset user config

---

src/app/models/SVGActionsFactory.js
src/app/ui/widgets/Macro/Macro.jsx
src/app/ui/widgets/Macro/index.jsx
src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx

[LU-1730](https://snapmaker2.atlassian.net/browse/LU-1730)
[LU-1719](https://snapmaker2.atlassian.net/browse/LU-1719)

Fix: Bugfix workspace macro input

---

src/app/flux/machine/Server.js
src/app/flux/machine/index.js
src/app/flux/workspace/index.js
src/app/ui/modals/modal-machine-select.jsx
src/app/ui/pages/CncLaserShared/MainToolBar.jsx
src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx
src/app/ui/widgets/Connection/SerialConnection.jsx
src/app/ui/widgets/Connection/WifiConnection.jsx
src/app/ui/widgets/Marlin/Marlin.jsx
src/app/ui/widgets/WifiTransport/WifiTransport.jsx
src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
src/server/controllers/Marlin/Marlin.js
src/server/controllers/constants.js

Improvement: Improve workspace state 

---

package.json

- Add laser svg point mode
- Fix png dual channel exception
- Fix bug for svg parse

Feature: Update engine

---

resources/CuraEngine/Config/printing/model.def.json
resources/CuraEngine/Config/printing/snapmaker2.def.json
resources/CuraEngine/Config/printing/snapmaker_extruder_1.def.json
src/app/api/index.js
src/app/flux/manager/DefinitionManager.js
src/app/flux/printing/index.js
src/app/flux/project/index.js
src/app/models/ThreeModel.js
src/server/services/api/api-profile-definitions.js
src/server/services/index.js
src/server/slicer/slice.js

[LU-1612](https://snapmaker2.atlassian.net/browse/LU-1612)

Feature: Add config for double extruder

---

src/app/flux/editor/index.js
src/app/models/ModelGroup.js
src/app/ui/components/SMCanvas/TransformControls.js
src/app/ui/widgets/WorkingProgress/WorkingProgress.jsx

[LU-1829](https://snapmaker2.atlassian.net/browse/LU-1829)

Fix: Bugfix v4.1 release 1

---

src/app/models/ModelGroup.js
src/app/three-extensions/ThreeUtils.js

[LU-1551](https://snapmaker2.atlassian.net/browse/LU-1551)

Improvement: Improve rotation placement plane

---

resources/CuraEngine/Config/printing/a150_single/material.abs.def.json
resources/CuraEngine/Config/printing/a150_single/material.petg.def.json
resources/CuraEngine/Config/printing/a150_single/material.pla.def.json
resources/CuraEngine/Config/printing/a150_single/quality.fast_print.def.json
resources/CuraEngine/Config/printing/a150_single/quality.high_quality.def.json
resources/CuraEngine/Config/printing/a150_single/quality.normal_quality.def.json
resources/CuraEngine/Config/printing/a250_single/material.abs.def.json
resources/CuraEngine/Config/printing/a250_single/material.petg.def.json
resources/CuraEngine/Config/printing/a250_single/material.pla.def.json
resources/CuraEngine/Config/printing/a250_single/quality.fast_print.def.json
resources/CuraEngine/Config/printing/a250_single/quality.high_quality.def.json
resources/CuraEngine/Config/printing/a250_single/quality.normal_quality.def.json
resources/CuraEngine/Config/printing/a350_single/material.abs.def.json
resources/CuraEngine/Config/printing/a350_single/material.petg.def.json
resources/CuraEngine/Config/printing/a350_single/material.pla.def.json
resources/CuraEngine/Config/printing/a350_single/quality.fast_print.def.json
resources/CuraEngine/Config/printing/a350_single/quality.high_quality.def.json
resources/CuraEngine/Config/printing/a350_single/quality.normal_quality.def.json
resources/CuraEngine/Config/printing/original_single/material.abs.def.json
resources/CuraEngine/Config/printing/original_single/material.petg.def.json
resources/CuraEngine/Config/printing/original_single/material.pla.def.json
resources/CuraEngine/Config/printing/original_single/quality.fast_print.def.json
resources/CuraEngine/Config/printing/original_single/quality.high_quality.def.json
resources/CuraEngine/Config/printing/original_single/quality.normal_quality.def.json
src/app/constants/index.js
src/app/ui/views/ProfileManager/index.jsx

Feature: Change 3dp materials and quality

---

src/app/flux/editor/index.js
src/app/flux/printing/index.js
src/app/models/ModelGroup.js
src/app/ui/SVGEditor/SVGCanvas.jsx
src/app/ui/pages/HomePage/QuickStart.jsx
src/app/ui/widgets/PrintingVisualizer/Visualizer.jsx
src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx

[LU-1862](https://snapmaker2.atlassian.net/browse/LU-1862)
[LU-1863](https://snapmaker2.atlassian.net/browse/LU-1863)
[LU-1864](https://snapmaker2.atlassian.net/browse/LU-1864)
[LU-1537](https://snapmaker2.atlassian.net/browse/LU-1537)
[LU-883](https://snapmaker2.atlassian.net/browse/LU-883)
[LU-1019](https://snapmaker2.atlassian.net/browse/LU-1019)

Fix: bugfix v4.1 left issue-1

---

.gitattributes
.github/workflows/build-on-create-release.yml
gulp/tasks/app.js
gulp/tasks/server.js
package-lock.json
src/shared/lib/DXFParser/DxfArrayScanner.js

Github Actions workflow pass, see: https://github.com/parachvte/Luban/actions/runs/1526346253

Fix: Fix npm dependency conflicts

---

src/app/flux/editor/index.js
src/app/flux/laser/index.js
src/app/models/ModelGroup.js
src/app/ui/widgets/LaserStackedModel/index.jsx

[LU-1874](https://snapmaker2.atlassian.net/browse/LU-1874)
[LU-1881](https://snapmaker2.atlassian.net/browse/LU-1881)
[LU-1889](https://snapmaker2.atlassian.net/browse/LU-1889)

Fix: Bugfix v4.1.1 alpha-1

---

package.json
resources/CuraEngine/Config/printing/snapmaker.def.json
resources/CuraEngine/Config/printing/snapmaker2.def.json

- Update 3DP speed config
- Add Laser and CNC time estimate

Build: Bump luban engine’s version to 0.7.0

---

gulp/tasks/server.js
src/server/webpack-dev-server.js

[LU-1800](https://snapmaker2.atlassian.net/browse/LU-1800)

Refactor: Debug in ElectronJS

---

src/app/ui/widgets/CNCVisualizer/Visualizer.jsx
src/app/ui/widgets/CNCVisualizer/styles.styl
src/app/ui/widgets/LaserVisualizer/Visualizer.jsx
src/app/ui/widgets/LaserVisualizer/styles.styl
src/app/ui/widgets/styles.styl

[LU-1850](https://snapmaker2.atlassian.net/browse/LU-1850)

Fix: Fix canvas-wrap-position

---

src/app/flux/manager/DefinitionManager.js
src/app/flux/printing/index.js

Improvement: Add extruder parameters in mesh definition file

---

src/app/flux/machine/index.js
src/app/flux/printing/index.js
src/app/three-extensions/TextSprite.js
src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx
src/app/workers/GcodeToBufferGeometry/GcodeToBufferGeometryPrint3d.js

Fix: Fix bug on v4.1.3

---

src/app/flux/machine/index.js
src/app/three-extensions/TargetPoint.js
src/app/ui/components/Select/styles.styl
src/app/ui/views/ToolPathConfigurations/cnc/ToolSelector.jsx
src/app/ui/widgets/WifiTransport/WifiTransport.jsx

Fix: Fix 10w-laser start print position error

---

package-lock.json
package.json
src/app/flux/editor/actions-process.js
src/app/flux/editor/index.js
src/app/flux/workspace/index.js
src/app/models/BaseModel.ts
src/app/models/ModelGroup.js
src/app/models/SvgModel.js
src/app/models/ThreeBaseModel.ts
src/app/models/ThreeModel.js
src/app/toolpaths/ToolPath.js
src/app/ui/SVGEditor/PrintableArea.js
src/app/ui/SVGEditor/svg-content/SVGContentGroup.js
src/package.json
src/server/services/api/api-commands.js
src/server/services/api/api-events.js
src/server/services/api/api-file.js
src/server/services/api/api-macros.js
src/server/services/api/api-users.js
src/server/services/configstore/index.js
tsconfig.json

Upgrade the uuid version and correct uuid usage

Fix: Fix loading file bug on laser and cnc

---

src/app/resources/i18n/de/resource.json

Insert an improved german translation

Improvement: Improve to update resource.json

---

src/app/constants/index.js
src/app/flux/printing/index.js
src/app/lib/check-name.js
src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
src/server/services/configstore/index.js
src/shared/lib/SVGParser/AttributesParser.js
src/shared/lib/SVGParser/Parser.js
src/shared/lib/SVGParser/TextParser.js
src/shared/lib/SVGParser/constants.js

Fix: Fix serveral bug in v4.2.0

---

src/app/flux/operation-history/DeleteOperation2D.js
src/app/flux/printing/index.js
src/app/ui/widgets/PrintingVisualizer/Overlay/RotationAnalysisOverlay.jsx

[LU-2106](https://snapmaker2.atlassian.net/browse/LU-2106)
[LU-2110](https://snapmaker2.atlassian.net/browse/LU-2110)
[LU-2109](https://snapmaker2.atlassian.net/browse/LU-2109)

Fix: Fix generate gcode button disabled when undo removing in laser & rotation analysis clear supports

---

package.json
src/app/ui/views/ToolPathConfigurations/ToolPathFastConfigurations.jsx
src/app/ui/widgets/CncLaserList/ToolPathList/ToolPathListBox.jsx

Fix: Fix the bug that changing general parameters does not take effect on ui

Build: Change electron-rebuild version to fix rebuilding failure on Windows

---

src/app/flux/editor/index.js
src/app/flux/printing/index.js
src/app/lib/controller.js
src/app/lib/manager/ProgressManager.js
src/app/models/ModelGroup.js
src/app/models/ThreeGroup.ts
src/app/models/ThreeModel.js
src/app/ui/pages/Laser.jsx
src/app/ui/widgets/Console/Console.jsx
src/server/services/index.js
src/server/services/task-manager/Task.ts
src/server/services/task-manager/TaskManager.ts
src/shared/lib/SVGParser/AttributesParser.js

[LU-2172](https://snapmaker2.atlassian.net/browse/LU-2172)
[LU-2175](https://snapmaker2.atlassian.net/browse/LU-2175)
[LU-2166](https://snapmaker2.atlassian.net/browse/LU-2166)
[LU-2176](https://snapmaker2.atlassian.net/browse/LU-2176)
[LU-2180](https://snapmaker2.atlassian.net/browse/LU-2180)
[LU-2028 issue-3](https://snapmaker2.atlassian.net/browse/LU-2028)

Fix: Model mirror clear support & material incorrect after editing support & model cut progress bar description

---

src/server/services/api/api-image.js
src/server/services/task-manager/workers/loadSize.js

[LU-2195](https://snapmaker2.atlassian.net/browse/LU-2195)

Fix: Fix error listening for loadsize worker

---

src/app/flux/operation-history/DeleteOperation3D.ts
src/app/flux/operation-history/MoveOperation3D.ts
src/app/flux/printing/index.js
src/app/models/ModelGroup.js
src/app/models/ThreeGroup.ts

[LU-2192](https://snapmaker2.atlassian.net/browse/LU-2192)

Fix: Fix lost model before record

---

src/app/models/ModelGroup.js

[LU-2206](https://snapmaker2.atlassian.net/browse/LU-2206)

Fix: Fix support overhang angle in 3D printing

---

src/app/workers/GcodeToBufferGeometry/GcodeToBufferGeometryPrint3d.js
src/shared/lib/gcodeToolPath.js

Fix: Fix when gcode'e is equal to - 1, it should be travel

---

src/app/flux/machine/index.js

[LU-2214](https://snapmaker2.atlassian.net/browse/LU-2214)

Improvement: Change z position in 10w-laser 3-axis auto mode

---

src/app/ui/widgets/PrintingVisualizer/PrintableCube.jsx

[LU-2133](https://snapmaker2.atlassian.net/browse/LU-2133)

Improvement: Change 3dp printable area three objects

---

src/shared/lib/DXFParser/Parser.js
src/shared/lib/DXFParser/bSpline.js
src/shared/lib/DXFParser/round10.js

https://snapmaker2.atlassian.net/browse/LU-2194

Fix: Fix some case of dxf spline parsing

---

src/app/flux/manager/DefinitionManager.js
src/app/flux/printing/index.js

[LU-2211](https://snapmaker2.atlassian.net/browse/LU-2211)

Fix: 3dp gcode temperature invalid

---

src/app/constants/copy.js
src/app/resources/i18n/cs/resource.json
src/app/resources/i18n/de/resource.json
src/app/resources/i18n/en/resource.json
src/app/resources/i18n/es/resource.json
src/app/resources/i18n/fr/resource.json
src/app/resources/i18n/hu/resource.json
src/app/resources/i18n/it/resource.json
src/app/resources/i18n/ja/resource.json
src/app/resources/i18n/ko/resource.json
src/app/resources/i18n/pt-br/resource.json
src/app/resources/i18n/ru/resource.json
src/app/resources/i18n/uk/resource.json
src/app/resources/i18n/zh-cn/resource.json
src/app/resources/i18n/zh-tw/resource.json

https://snapmaker2.atlassian.net/browse/LU-2228

Fix: Fix profile manager translation error

---

src/app/models/ModelGroup.js
src/app/ui/widgets/PrintingVisualizer/Overlay/SupportOverlay.jsx
src/app/ui/widgets/PrintingVisualizer/Overlay/TranslationOverlay.jsx
src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx

[LU-2227](https://snapmaker2.atlassian.net/browse/LU-2227)

Fix: Fix Laser & CNC delete object error

---

src/server/DataStorage.js
src/server/app.js
src/server/config/settings.base.js
src/server/services/api/api-file.js
src/server/services/api/api-image.js
src/server/services/api/api-profile-definitions.js
src/server/services/api/api-svg.js
src/server/services/api/api-users.js
src/server/services/api/api-utils.js
src/server/services/index.js
src/server/services/task-manager/TaskManager.ts
src/server/slicer/definition.js
src/server/slicer/slice.js

[LU-2230](https://snapmaker2.atlassian.net/browse/LU-2230)

Refactor: Unify log format & add error catch on server side

---

.github/workflows/build-on-create-release.yml

[https://github.com/parachvte/Luban/releases/tag/v4.3.0-Fix-windows-pack](https://github.com/parachvte/Luban/releases/tag/v4.3.0-Fix-windows-pack)

Fix: Fix Windows package build by installing VC++ runtime

---

src/app/flux/editor/actions-process.js
src/app/flux/editor/index.js
src/app/models/ThreeModel.js
src/app/store/local-storage.js
src/app/styles/contextmenu.styl
src/app/ui/components/Select/ChangedReactSelect.jsx
src/app/ui/views/ProfileManager/ConfigValueBox.jsx
src/app/ui/views/ProfileManager/SettingItem.jsx
src/server/DataStorage.js

[LU-2256](https://snapmaker2.atlassian.net/browse/LU-2256)
[LU-2252](https://snapmaker2.atlassian.net/browse/LU-2252)
[LU-1698](https://snapmaker2.atlassian.net/browse/LU-1698)
[LU-2236](https://snapmaker2.atlassian.net/browse/LU-2236)

Fix: Retraction switch & Laser multi toolPath slice & UI Z order & switch model color when editing support

---

src/app/flux/editor/actions-base.js
src/app/flux/manager/DefinitionManager.js
src/app/flux/printing/index.js
src/app/models/SvgModel.js
src/app/ui/views/ProfileManager/ConfigValueBox.jsx

Fix: Fix several params doesn't work in some case
Fix: Fix copying inner text doesn't work as result
Fix: Fix  UI bugs
https://snapmaker2.atlassian.net/browse/LU-2272
https://snapmaker2.atlassian.net/browse/LU-2253
https://snapmaker2.atlassian.net/browse/LU-2263
https://snapmaker2.atlassian.net/browse/LU-2122

Fix: Fix several params doesn't work in some case & UI bugs

---

src/app/styles/global-border.styl
src/app/ui/widgets/PrintingVisualizer/Overlay/TranslateOverlay.jsx
src/app/ui/widgets/PrintingVisualizer/Overlay/styles.styl

https://snapmaker2.atlassian.net/browse/LU-2257

Style: Change translateOverlay style

---

src/app/ui/components/Select/ChangedReactSelect.jsx
src/app/ui/views/ProfileManager/ConfigValueBox.jsx
src/app/ui/views/ProfileManager/SettingItem.jsx

[LU-2282](https://snapmaker2.atlassian.net/browse/LU-2282)

Fix: Select dropdown filter unavailable

---

src/app/ui/components/SMCanvas/Canvas.jsx
src/app/ui/components/SMCanvas/Controls.jsx

https://snapmaker2.atlassian.net/browse/LU-2276

Fix: Update 3d camera scale & translate bug

---

src/app/styles/global-edge-distance.styl
src/app/ui/components/Steps/index.js
src/app/ui/pages/HomePage/styles.styl
src/app/ui/views/ProfileManager/SettingItem.jsx
src/app/ui/widgets/PrintingVisualizer/Overlay/EditSupportOverlay.jsx
src/app/ui/widgets/PrintingVisualizer/Overlay/ExtruderOverlay.jsx
src/app/ui/widgets/PrintingVisualizer/Overlay/MirrorOverlay.jsx
src/app/ui/widgets/PrintingVisualizer/Overlay/RotateOverlay.jsx
src/app/ui/widgets/PrintingVisualizer/Overlay/ScaleOverlay.jsx
src/app/ui/widgets/PrintingVisualizer/Overlay/SupportOverlay.jsx
src/app/ui/widgets/PrintingVisualizer/Overlay/TranslateOverlay.jsx
src/app/ui/widgets/PrintingVisualizer/Overlay/styles.styl
src/main.js

- https://snapmaker2.atlassian.net/jira/software/projects/LU/boards/7?selectedIssue=LU-2309
- https://snapmaker2.atlassian.net/jira/software/projects/LU/boards/7?selectedIssue=LU-1947
- https://snapmaker2.atlassian.net/jira/software/projects/LU/boards/7?selectedIssue=LU-2326

Fix : Fix UI 4.3.0

---

src/app/flux/machine/Server.js
src/app/ui/App.jsx
src/app/ui/widgets/Connection/WifiConnection.jsx
src/server/services/socket/ConnectionManager.js
src/server/services/socket/socket-http.ts

[LU-2267](https://snapmaker2.atlassian.net/browse/LU-2267)
[LU-2268](https://snapmaker2.atlassian.net/browse/LU-2268)

Fix: Cancel heartbeat after browser window reload

---

src/app/three-extensions/ThreeUtils.js

[LU-1940](https://snapmaker2.atlassian.net/browse/LU-1940)

Fix: Fix rotate by plane stucked

---

.github/workflows/build-on-create-release.yml
src/app/flux/machine/index.js
src/app/lib/uni-api.js
src/server/services/socket/socket-http.ts
src/server/services/task-manager/workers/heartBeat.ts

https://snapmaker2.atlassian.net/browse/LU-2442
https://snapmaker2.atlassian.net/browse/LU-2458

Fix: Fix firmware compatibility and maintool bar bug on macOS

---

.github/workflows/build-on-create-release.yml
src/app/constants/index.js
src/app/flux/machine/action-discover.js
src/app/index.jsx
src/app/models/ThreeModel.js
src/app/ui/widgets/Connection/WifiConnection.jsx
src/app/ui/widgets/Marlin/Printing.jsx
src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
src/server/DataStorage.js
src/server/controllers/Marlin/Marlin.js
src/server/lib/SocketManager/index.ts
src/server/services/api/api-image.js
src/server/services/index.js
src/server/services/socket/WifiServerManager.js
src/shared/lib/DXFParser/Parser.js

Fix: Fix extra auto-connect when swtiching page if is connected

---

.github/workflows/winget.yml

This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.
Before merging this:
1. Please add a GitHub token with `public_repo` scope as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @Snapmaker.

Build: Publish to Windows Package Managar (WinGet)

---

.github/workflows/build-on-create-release.yml
build/pkgsync.js
build/set-config.js
gulp/tasks/app.js
gulp/tasks/server.js
package.json
src/app/index.jsx
src/app/ui/App.jsx
src/main.js
src/package.json
src/server/index.js
webpack.config.app.production.js
webpack.config.server.production.js

[Fix: Renderer process crashes on power resume](https://github.com/electron/electron/pull/35322)
Fix: Ignore check updates for Linux platforms

Improvement: Improvement error monitoring

---

gulp/tasks/i18next.js

MIssing commit in https://github.com/Snapmaker/Luban/pull/1816

Fix: Fix eslint errors in code

---

src/app/flux/machine/Server.js
src/server/services/socket/sacp/SACP-TCP.ts

Fix: Fix bugs for Snapmaker J1 network connections

---

src/app/flux/machine/Server.js
src/app/flux/machine/action-connect.js
src/app/flux/machine/index.js
src/app/ui/widgets/Connection/WifiConnection.jsx

The quick fix solution in https://github.com/Snapmaker/Luban/issues/1824

Improvement: Improve networked printer auto connect

---

src/app/ui/components/Modal/index.jsx
src/app/ui/layouts/Widget/index.jsx
src/app/ui/pages/Workspace.jsx
src/app/ui/widgets/LaserTestFocus/index.jsx
src/server/services/socket/socket-http.ts

Update docs by https://github.com/parachvte/ProfileDocs/pull/1

Docs: Update profile docs

---

src/app/flux/machine/Server.js
src/app/flux/machine/action-connect.js
src/app/flux/machine/index.js
src/app/flux/workspace/index.js
src/app/three-extensions/ManualCalibrationControls.js
src/app/ui/pages/Workspace.jsx
src/app/ui/widgets/Connection/MismatchModal.jsx
src/app/ui/widgets/Connection/WifiConnection.jsx
src/app/ui/widgets/Marlin/Printing.jsx
src/app/ui/widgets/WifiTransport/WifiTransport.jsx
src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
src/server/services/socket/ConnectionManager.js
src/server/services/socket/socket-http.ts

* Fix: Fix mismatched dual extruder tool head

Fix: Fix networked printer issues

---

.github/workflows/build-on-create-release.yml
electron-builder.yml
package.json

https://github.com/Snapmaker/Luban/issues/617

Build: Add arm64 build for macOS (Draft)

---

src/main.js

Fix: Fix linux executable by adding --no-sandbox option to electron

---

src/app/flux/printing/index.js
src/shared/lib/SVGParser/Parser.js

https://github.com/Snapmaker/Luban/issues/1884
https://github.com/Snapmaker/Luban/issues/1879

Fix: Revert SVG bounding box recalculation

---

.gitmodules
build/prebuild-dev.sh
build/prebuild-prod.sh
package-lock.json
package.json
src/app/api/index.js
src/app/ui/views/PresetModifier/ParametersTableView.tsx
src/package.json
src/server/DataStorage.js
src/server/services/api/api-profile-definitions.js
src/server/services/api/api-users.js
src/server/services/index.js

Execute following on existing repo (after update to latest git HEAD):
```
git submodule init
git submodule update
rm -rf resources/ProfileDocs
```
Checklist:

Refactor: Move setting docs folder

---

.github/workflows/build-on-create-release.yml

https://help.aliyun.com/document_detail/179388.htm

Fix: Fix OSS upload wildcard path

---

src/app/models/ModelGroup.ts
src/app/ui/components/SMCanvas/Canvas.jsx

In additional to PR: https://github.com/Snapmaker/Luban/pull/1965

Fix: Fix Artisan hot zone detection right after auto rotate (2)

---

package.json
src/app/config/menu/helpMenu.js
src/app/constants/copy.js
src/app/constants/index.ts
src/app/flux/appbar-menu/index.js
src/app/resources/i18n/cs/resource.json
src/app/resources/i18n/de/resource.json
src/app/resources/i18n/en/resource.json
src/app/resources/i18n/es/resource.json
src/app/resources/i18n/fr/resource.json
src/app/resources/i18n/hu/resource.json
src/app/resources/i18n/it/resource.json
src/app/resources/i18n/ja/resource.json
src/app/resources/i18n/ko/resource.json
src/app/resources/i18n/pt-br/resource.json
src/app/resources/i18n/ru/resource.json
src/app/resources/i18n/uk/resource.json
src/app/resources/i18n/zh-CN/resource.json
src/app/resources/i18n/zh-tw/resource.json
src/app/ui/layouts/AppLayout.jsx
src/package.json
src/server/services/index.js
src/server/services/socket/ConnectionManager.js
src/server/services/socket/socket-http.ts

- Fix bug for slicer error
- Add wifi test log

Feature:  Fix bug for slicer error

---

src/app/flux/printing/index.ts
src/app/ui/widgets/PrintingOutput/Output.tsx

Fixes https://github.com/Snapmaker/Luban/issues/2109

Fix: Fix unable to generate G-code on right extruder parameter changes

---

src/app/flux/printing/actions-scene.ts
src/app/models/ModelGroup.ts
src/app/models/PrimeTowerModel.ts
src/app/scene/scene.logic.ts
src/app/ui/widgets/PrintingOutput/Output.tsx

Fixes https://github.com/Snapmaker/Luban/issues/2123

Fix: Fix wrong prime tower calculation on no mesh

---

src/shared/lib/3MFLoader.js

Add to https://github.com/Snapmaker/Luban/pull/2129

Fix: Support all units defined in 3MF spec

---

package-lock.json
package.json
src/app/constants/index.ts
src/app/constants/machines.ts
src/app/flux/workspace/index.ts
src/app/ui/components/EditComponent/EditComponent.tsx
src/app/ui/components/Modal/index.tsx
src/app/ui/pages/Workspace.jsx
src/app/ui/widgets/ConnectionToolControl/PrintToolControl.tsx
src/package.json
src/server/services/socket/sacp/SACP-BASE.ts
src/server/services/socket/sacp/SACP-SERIAL.ts
src/server/services/socket/sacp/SACP-TCP.ts

https://github.com/Snapmaker/Luban/issues/1919

Feature: Add J1 extruder temperature control

---

src/app/ui/pages/Workspace.jsx
src/app/ui/widgets/ConnectionToolControl/PrintToolControl.tsx
src/app/ui/widgets/Enclosure/Enclosure.jsx
src/server/services/socket/sacp/SACP-BASE.ts
src/server/services/task-manager/workers/generateToolPath.ts

https://github.com/Snapmaker/Luban/issues/1919

Improvement: Add heated bed control for J1 & Artisan

---

package-lock.json
package.json
src/app/flux/app-global/index.js
src/app/flux/printing/actions-mesh.ts
src/app/flux/printing/actions-scene.ts
src/app/flux/printing/index.ts
src/app/models/ModelGroup.ts
src/app/models/ThreeModel.ts
src/app/scene/three-extensions/Detector.ts
src/app/ui/components/SMCanvas/Canvas.tsx
src/app/ui/components/SMCanvas/Controls.ts
src/app/ui/views/Cnc3DVisualizer/Canvas/Controls.jsx
src/app/ui/views/model-operation-overlay/EditSupportOverlay.jsx
src/app/ui/views/model-operation-overlay/MeshColoringOverlay.tsx
src/app/ui/views/model-operation-overlay/MirrorOverlay.jsx
src/app/ui/views/model-operation-overlay/ModelScaleOverlay.tsx
src/app/ui/views/model-operation-overlay/RotateOverlay.jsx
src/app/ui/views/model-operation-overlay/SupportOverlay.tsx
src/app/ui/views/model-operation-overlay/TranslateOverlay.jsx
src/app/ui/widgets/ConnectionFileTransfer/FileTransferView.tsx
src/app/ui/widgets/PrintingVisualizer/SceneView.jsx
src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx
src/app/ui/widgets/PrintingVisualizer/styles.styl
src/app/ui/widgets/styles.styl
src/package.json

Fixes https://github.com/Snapmaker/Luban/issues/2191

Fix: Fis minor issues related to v4.8.0

---

src/app/flux/project/index.js
src/app/ui/layouts/AppLayout.jsx
src/server/index.ts
src/server/lib/logger.ts

Fixes https://github.com/Snapmaker/Luban/issues/2184

Fix: Fix project save dialog behavior

---

src/app/core/OperationHistory.ts
src/app/flux/editor/index.ts

Fixes 
https://github.com/Snapmaker/Luban/issues/2202

Fix: Fix operation history caused Pen tool crash

---

src/app/models/ModelGroup.ts
src/app/scene/operations/AlignGroupOperation.ts
src/app/ui/views/PrintingObjectList/ObjectListView.tsx
src/app/ui/widgets/PrintingVisualizer/VisualizerPreviewControl.jsx

Fixes https://github.com/Snapmaker/Luban/issues/2090

Fix: Fix model alignment when they are rotated / scaled

---

src/app/flux/workspace/Server.js
src/app/flux/workspace/index.ts
src/app/flux/workspace/state.ts
src/app/lib/controller.ts
src/app/resources/i18n/cs/resource.json
src/app/resources/i18n/de/resource.json
src/app/resources/i18n/en/resource.json
src/app/resources/i18n/es/resource.json
src/app/resources/i18n/fr/resource.json
src/app/resources/i18n/hu/resource.json
src/app/resources/i18n/it/resource.json
src/app/resources/i18n/ja/resource.json
src/app/resources/i18n/ko/resource.json
src/app/resources/i18n/pt-br/resource.json
src/app/resources/i18n/ru/resource.json
src/app/resources/i18n/uk/resource.json
src/app/resources/i18n/zh-CN/resource.json
src/app/resources/i18n/zh-tw/resource.json
src/app/ui/pages/Workspace.jsx
src/app/ui/widgets/Connection/NetworkConnection.tsx
src/server/app.js
src/server/index.ts
src/server/lib/SocketManager/index.ts
src/server/lib/image-getPhoto.js
src/server/services/channel-handlers/mesh.ts
src/server/services/index.ts
src/server/services/machine/index.ts
src/server/services/socket/ConnectionManager.js
src/server/services/socket/ConnectionManager.ts
src/server/services/socket/socket-http.ts

Refactor: Refactor 2.0 connection logic

---

src/app/flux/printing/actions-scene.ts
src/app/models/ModelGroup.ts
src/app/scene/controls/MeshColoringControl.ts
src/app/ui/views/model-operation-overlay/MeshColoringOverlay.tsx
src/app/ui/widgets/PrintingVisualizer/VisualizerLeftBar.jsx

Fix https://github.com/Snapmaker/Luban/issues/2198

Fix: Fix wrong mesh color slicing result

---

src/app/flux/manager/DefinitionManager.js

Fixes https://github.com/Snapmaker/Luban/issues/2207

Fix: Fix recalculation of nozzle size to line width

---

src/app/machines/snapmaker-a250.ts
src/app/machines/snapmaker-a350.ts
src/app/machines/snapmaker-artisan.ts

(Copied from 10W print settings)

Feature: Initialize 20W & 40W laser print settings

---

package.json
src/app/constants/index.ts
src/app/ui/views/ToolPathConfigurations/ToolPathConfigurations.jsx
src/app/ui/views/ToolPathConfigurations/ToolPathFastConfigurations.jsx
src/app/ui/views/ToolPathConfigurations/laser/GcodeParameters.jsx
src/package.json
src/server/lib/GcodeGenerator/GcodeGenerator.js
src/server/services/task-manager/workers/generateToolPath.ts

- Fix bug for marlin laser point mode
- Fix bug for M2000 W1 P100

Feature: Add parameter halfDiodeMode

---

package.json
src/app/constants/index.ts
src/app/workers/GcodeToBufferGeometry/GcodeToBufferGeometryWorkspace.js
src/package.json
src/server/lib/GcodeGenerator/GcodeGenerator.js
src/server/services/task-manager/workers/generateGcode.js
src/shared/lib/gcodeToolPath.js

- Fix bug for laser profile manager
- Fix bug for G4 P

Fix: Fix bug for workspace laser preview

---

src/app/flux/appbar-menu/index.ts
src/app/flux/workspace/index.ts
src/app/ui/widgets/Connection/NetworkConnection.tsx
src/app/ui/widgets/ConnectionControl/Control.tsx
src/app/ui/widgets/Console/Console.jsx
src/app/ui/widgets/RaySetOriginWidget/SetOriginView.tsx
src/app/ui/widgets/RayUploadWidget/UploadView.tsx
src/app/ui/widgets/WorkspaceVisualizer/Visualizer.jsx
src/server/constants/index.js
src/server/lib/ScheduledTasks/index.ts
src/server/services/machine/ConnectionManager.ts
src/server/services/machine/MachineDiscoverer.ts
src/server/services/machine/ProtocolDetector.ts
src/server/services/machine/channels/Channel.ts
src/server/services/machine/channels/SacpChannel.ts
src/server/services/machine/channels/SacpTcpChannel.ts
src/server/services/machine/channels/SstpHttpChannel.ts
src/server/services/machine/channels/TextSerialChannel.ts
src/server/services/machine/instances/ArtisanInstance.ts
src/server/services/machine/instances/J1Instance.ts
src/server/services/machine/instances/RayInstance.ts
src/server/services/machine/instances/SM2Instance.ts
src/server/services/machine/types.ts
src/server/services/socket/discover-handlers.ts
src/server/services/socket/machine-handlers.ts

- Fix unable to resume job (SM 2.0)
- Fix ray flashing with M3 S0

Fix: Fix several minor issues & connection code refactor

---

src/app/ui/pages/HomePage/styles.styl

- Fix: Information flow block style shake
- Fix: Information flow block Small window img not auto fill parent box

Fix v4.9.0 informationflow-style

---

package.json
src/package.json

- Fix the issue of incorrect laser printing speed

Feature: Update lunar to 1.4.4

---

src/app/flux/editor/index.ts
src/app/ui/SVGEditor/SVGEditor.tsx
src/app/ui/SVGEditor/SVGShapeLibrary/styles.styl
src/app/ui/pages/HomePage/styles.styl
src/app/ui/widgets/CNCVisualizer/Visualizer.tsx
src/app/ui/widgets/LaserVisualizer/Visualizer.tsx

- home page Case lib block layout
- cnc open SvgShapeLib

Fix 4.9.1 svg shape lib

---

src/app/ui/pages/laser-main/modals/JobSetupView.tsx
src/app/ui/widgets/ConnectionFileTransfer/FileTransferView.tsx
src/app/ui/widgets/ConnectionFileTransfer/LaserStartModal.tsx
src/server/controllers/Marlin/MarlinController.js
src/server/services/machine/ConnectionManager.ts
src/server/services/machine/channels/SacpSerialChannel.ts
src/server/services/machine/channels/TextSerialChannel.ts

* Use M3 S0.2 for 20W & 40W laser module
* Fix start job G-code (serial port + manual mode)
* Fix A400 serial port detection (in case not switching to SACP)
* Hide origin offset mode for SM 2.0
* Hide semi auto mode for 20W/40W

Fix: Fix several minor issues

---

package.json

Feature: Update lunar to 1.4.6

---

src/app/flux/printing/index.ts
src/app/scene/three-extensions/STLLoader.js
src/shared/lib/SVGParser/Parser.js

- [Fix: Apply model scale twice in the Open 3DP project file](https://github.com/Snapmaker/Luban/commit/91a401dfc8200f3d488ef819a3d4de1fac43ea03)
- [Fix: Svg parse failed when svg has non-standard element](https://github.com/Snapmaker/Luban/commit/f90bda219fc24ce0eac430036c0be1b561be95c6)
- [Fix: Can't import stl to laser](https://github.com/Snapmaker/Luban/commit/3d890aeb69ab21b167003cc92b682a8b8d5ca3b8)

Fix: v4.10.2 part3

---

package.json
src/server/services/machine/ProtocolDetector.ts
src/shared/lib/BufferGeometryUtils.js

Fix: 4.10.2 part6

---

src/app/flux/workspace/index.ts
src/app/ui/widgets/Connection/NetworkConnection.tsx
src/app/ui/widgets/Connection/modals/SelectMachineModal.tsx
src/app/ui/widgets/ConnectionFileTransfer/FileTransferView.tsx
src/app/ui/widgets/Enclosure/Enclosure.tsx
src/server/controllers/Marlin/MarlinController.js
src/server/services/machine/channels/SacpChannel.ts
src/server/services/machine/channels/SacpSerialChannel.ts
src/server/services/machine/instances/RayInstance.ts
src/server/services/machine/sacp/SacpClient.ts

- fix: J1 enclosure light state
- [Fix: J1 get enclosure light state](https://github.com/Snapmaker/Luban/commit/a1f785650084d28a43cbcec3e07eec7e7e8218a3)
- [Fix: Hidden fan when connect with j1](https://github.com/Snapmaker/Luban/commit/03112d8f9478598e45a7ea0e8f171b4f65f1b2ba)
- [Fix: Ray Can't get enclosure, rotatry, ari purifier status connect with wifi/serial](https://github.com/Snapmaker/Luban/commit/0610978f29222afdf8ac4d761be3e1587981b194)
- [Fix: Wifi connection aifpurifier status](https://github.com/Snapmaker/Luban/pull/2453/commits/379dc8e60021c0caaff2da1de46d70803069d9d8)
- [Fix: Original serial connect failed](https://github.com/Snapmaker/Luban/commit/4a7c925db97d38e23492b92e33b7cd3f774162e4)

Fix: v4.10.2 part4

---

package-lock.json
package.json
src/package.json

Fix: Fix lunarTPP auth bug

---

.github/workflows/build-on-pull-request.yml
package.json

Just auto run at push
Fix no mac-x64 BUG

Fix: Fix workflow bu

---

.github/workflows/build-on-create-release.yml
.github/workflows/build-on-pull-request.yml
package-lock.json
package.json
src/app/flux/editor/index.ts
src/app/resources/i18n/cs/resource.json
src/app/resources/i18n/de/resource.json
src/app/resources/i18n/en/resource.json
src/app/resources/i18n/es/resource.json
src/app/resources/i18n/fr/resource.json
src/app/resources/i18n/hu/resource.json
src/app/resources/i18n/it/resource.json
src/app/resources/i18n/ja/resource.json
src/app/resources/i18n/ko/resource.json
src/app/resources/i18n/pt-br/resource.json
src/app/resources/i18n/ru/resource.json
src/app/resources/i18n/uk/resource.json
src/app/resources/i18n/zh-CN/resource.json
src/app/ui/pages/CncLaserShared/MainToolBar.tsx
src/app/ui/pages/laser-main/LaserMainPage.tsx
src/app/ui/views/MaterialTesting/FormStyles.styl
src/app/ui/views/MaterialTesting/MaterialTestingModal.tsx
src/app/ui/views/MaterialTesting/MaterialTestingView.tsx
src/package.json
src/server/lib/svg-convert.js

Support Laser material testing

Laser material testing

---

.github/workflows/build-on-pull-request.yml

Fix Wrong nightly build

---

.github/workflows/build-on-create-release.yml
.github/workflows/build-on-pull-request.yml
build/notarize.js

Update Notarizing config
(cherry picked from commit 52fecd5e4a24942577bdaded142c74de13277cd9)

Feature: Update Notarizing config
