.eslintignore, package-lock.json, package.json, src/app/styles/xterm.styl, src/app/widgets/Console/Terminal.jsx
Terminal code update to latest xterm major 4.x
This is a fix for #254 and I've added some additional notes as well in the thread.
I'm not a JS Engineer, so maybe it needs some tweaks.
Copy and paste in the console window should work now, you can also Select All. 
Managed to get the electron build running, works well 👍 
For fun, I tested the local dev server with latest versions of Edge, Chrome, Firefox. Safari in Windows and Mac.
This recording was with the Chrome Version Version 80.0.3987.163 (Official Build) (64-bit) in Catalina (10.15.4)
=> Improvement: Fix copy/paste when using the console

src/app/flux/printing/index.js
uploadName changes to stlFileName from the first upload model's uploadName
=> Fix: Fix 3DPrint .obj file cannot be sliced

package-lock.json, package.json, src/app/widgets/CNCVisualizer/styles.styl, src/app/widgets/CncLaserObjectList/styles.styl, src/app/widgets/CncLaserSvgEditor/index.styl, src/app/widgets/LaserVisualizer/styles.styl, src/package.json, src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js, src/server/slicer/slice.js
- Use material_print_temperature_layer_0 instead of material_print_temperature in the gcode header
- Don`t use optimizePath when svg shapes length > 2000
=> Build: Build br for v3.7.0

src/shared/lib/SVGParser/AttributesParser.js
`a.76.76,0,0,0` was parsed into [a, 0.76, 0, 0, 0] in previous implementation, results in number of tokens are not aligned, the shape is missing from parse result.
With coding changes, `a.76.76,0,0,0` should be parsed as  [a, 0.76, 0.76, 0, 0, 0].
Sample:
```SVG
<svg id="图层_1" data-name="图层 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 737.01 963.78">
<rect class="cls-1" width="737.01" height="963.78"/>
<path class="cls-1" d="M67.63,259.62a.76.76,0,0,0,.08.32,1.06,1.06,0,0,1,.08.49l-24,24q.5,4.38.9,9.16t.4,7.7q0,5.34-.16,13.53t-.49,19.37q1,15.88,2.43,29.59t3.25,23.9a157.58,157.58,0,0,0,8.59,29.75,87.15,87.15,0,0,0,12.64,22,51.08,51.08,0,0,0,16.53,13.7,44.45,44.45,0,0,0,20.43,4.7,62,62,0,0,0,40-14.26c.86-.76,1.72-1.49,2.59-2.19s1.73-1.49,2.59-2.35l9.24-9.4a62.19,62.19,0,0,0,4.3,7A71.7, …
```
=> Fix: Fix SVG numeric parsing

src/server/lib/ToolPathGenerator/SVGFill.js
This changes svg filling to generate segments per path in the svg this can greatly reduce the amount of time the head spends jogging for svgs containing many non overlapping spaced apart shapes. I have attached an example svg in this zip to demonstrate the improvement.
[example.zip](https://github.com/Snapmaker/Luban/files/5329757/example.zip)
=> Improvement: convert svg's component paths one at a time

src/app/flux/machine/index.js
It causes the machine not to disconnect from Wi-Fi when the machine is in "emergency stop" state.
=> Fix: Need to check that "ports" is empty or not when disconnect from Wi-FI

src/app/components/three-extensions/STLBinaryExporter.js, src/app/components/three-extensions/STLLoader.js, src/app/flux/printing/index.js, src/app/models/Model.js
- Do not clone Geometry and ConvexGeometry in Model.clone
- Loading only once when the same model copied in object list when
recovery
- Do not convert BufferGeometry to Geometry when export for slice
=> Perf: Improve memory usage of big files in 3dp

src/app/flux/editor/index.js, src/app/models/SVGActionsFactory.js, src/server/lib/ToolPathGenerator/CncToolPathGenerator.js, src/server/lib/ToolPathGenerator/LaserToolPathGenerator.js
- Fix laser/cnc toolpath size error when changing size in transformation widget
- Fix laser/cnc copied model processing config not being copied
- Fix laser/cnc scaled text toolpath size error when changing text in transformation widget
- Fix cnc toolpath flip error of svg
=> Fix: Fix several bugs for model configuration, wrong text size and wrong tool path size

src/app/flux/printing/index.js
It causes that the time clock is not destroyed.
=> Fix: Reset state to "displayModel" when destroy G-code line

src/app/flux/printing/index.js, src/app/flux/project/index.js, src/app/models/ModelGroup.js, src/app/widgets/PrintingOutput/Output.jsx, src/app/widgets/PrintingVisualizer/Visualizer.jsx, src/app/widgets/PrintingVisualizer/VisualizerModelTransformation.jsx
- Destroy Gcodeline when starting support mode
- Refresh transformation after auto rotate
- Show modal when failed to loading model
- Limit min value of support size
=> Fix: Fix bugs for 3dp

package.json, src/app/components/Checkbox/index.js, src/app/components/OptionalDropdown/OptionalDropdown.jsx, src/app/components/OptionalDropdown/styles.styl
This fixes #829.
The UI for the optional dropdown component is pretty confusing. When it's collapsed it shows a grayed out but checked checkbox. To me, that usually means the option is selected, but not changeable. That's not really what's happening, so I updated the UI to be a little more straight forward
There's still a checkbox as before (when selected): 
But now the unselected state is an empty checkbox:
I'll note that the above example is actually pretty weird from a UX perspective. Generally you'd use a checkbox to represent a user selection, but in the above example it's really just representing the expansion of the included panel. I didn't really dig into changing that though, just really wanted to keep it simple. 
For cases like selecting fill, multi-pass, etc from laser cutting …
=> Improvement: Use actual checkbox for optional dropdown

package-lock.json, package.json
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
```
Encountered this issue, we need to add `caniuse-list` to our package.json cause `npx browserslist@latest --update-db` is not actually working.
=> Improvement: Upgrade to lockfileVersion 2 using npm v7

src/shared/lib/SVGParser/AttributesParser.js
SVG files might have quotes in the font-family attribute. For example, when the font name contains spaces.
=> Fix: Remove quotes from font-family

src/shared/lib/SVGParser/AttributesParser.js
When parsing SVG files with 'style' attribute, the AttributesParser.parseAttribute recursively calls itself for every key:value block in 'style' attribute. 
The call invocation is missing last parameter, preventing 'style' attribute from being parsed correctly
=> Fix: Missing parameter in parseAttribute call

src/app/resources/i18n/cs/resource.json, src/app/resources/i18n/de/resource.json, src/app/resources/i18n/en/resource.json, src/app/resources/i18n/es/resource.json, src/app/resources/i18n/fr/resource.json, src/app/resources/i18n/hu/resource.json, src/app/resources/i18n/it/resource.json, src/app/resources/i18n/ja/resource.json, src/app/resources/i18n/ko/resource.json, src/app/resources/i18n/pt-br/resource.json, src/app/resources/i18n/ru/resource.json, src/app/resources/i18n/uk/resource.json, src/app/resources/i18n/zh-cn/resource.json, src/app/resources/i18n/zh-tw/resource.json, src/app/ui/pages/MachineMaterialSettings/MachineSettings.jsx
Added keys for left/right nozzle for the dual extruder nozzle diameter adjustment settings.
I've been trying to figure out for a while now why I can't get the labels for the left and right nozzles to translate properly in the dual extruder settings. The problem turned out to be that this part of the settings did not have its own parameters for translation. The keys used also for CNC are `key-Cnc/StlSection/orientation_Left-Left` and `key-Cnc/StlSection/orientation_Right-Right`. Here I present the changes that will eliminate this issue.
=> Improvement: Keys for left/right nozzle for the dual extruder

src/app/ui/layouts/AppLayout.jsx
This is a minor improvement that add missing white space between keys `key-app_layout-File Saved` and `key-app_layout-Open Folder` to the pop-up message when you saved g-code to a file.
```diff
-Filed savedOpen folder
+Filed saved. Open folder.
```
=> Improvement: Added white space at the end of sentence to the pop-up message when you saved g-code to a file.

src/app/flux/printing/actions-scene.ts, src/app/flux/printing/index.js, src/app/models/ModelGroup.ts, src/app/models/ThreeGroup.ts, src/app/ui/layouts/AppLayout.jsx, src/app/ui/views/PresetModifier/ParametersTableView.tsx, src/app/ui/views/PresetModifier/PresetContent.jsx, src/app/ui/views/PresetModifier/PresetModifierModal.jsx, src/app/ui/views/PresetModifier/StackPresetSelector.tsx, src/app/ui/widgets/CncLaserList/ObjectList/ObjectListBox.jsx, src/app/ui/widgets/CncLaserList/ObjectList/index.jsx, src/app/ui/widgets/CncLaserShared/VisualizerBottomLeft.jsx, src/app/ui/widgets/PrintingConfigurationWidget/ConfigurationView.tsx, src/app/ui/widgets/PrintingConfigurationWidget/PresetInitialization.tsx
Note:
- Also fixed prepend G-code in A150/A250/A350 with single extruder, the G-code attached in #1878 can used as example (but it's a different issue)
- Fix broken anchors on parameter table
=> Refactor: Unify use of preset models of left/right extruder

src/app/ui/pages/HomePage/MoreInfo.jsx
If the language is different from English, the link from the main window leads to the Chinese version of the site, store and support service.
=> Fix: Fix redirect for non-english links

README.md
Issue: The syntax to install a .deb package using dpkg is `dpkg --install [filename.deb]`. 
Solution: This commit adds the missing `--` to the codeblock within README.md which holds the example commands for installing via dpkg.
This commit does not affect any code, therefore no testing has been performed.
Found 0 issues of any status mentioning this, and 0 open PRs affecting README.md.
=> Correct syntax in README.md

.github/workflows/build-on-create-release.yml
1. npm v10 requires we upgrade Node.js to v18
2. Node.js v18 requires we upgrade all whole webpack to v5 immediately
3. Temporary solution: use npm v9 until we upgrade webpack to v5 (Node timeline: https://nodejs.dev/en/about/releases/)
=> Build: Fix build script by use npm@^9 instead of latest

electron-builder.yml
Suggest removing gconf2 gconf-service libappindicator1 as no longer needed  for gnome in Ubuntu  or Debian.    Without  removal, dpkg and/or apt will fail.
Upstream project documenation:  https://www.electron.build/configuration/linux#deb
`The following packages have unmet dependencies:
snapmaker-luban : Depends: gconf2 but it is not installable
Depends: gconf-service but it is not installable
Depends: libappindicator1 but it is not installable`
=> Improvement: removing gconf2 gconf-service libappindicator1

src/app/constants/index.ts, src/app/flux/editor/index.ts
- [Fix: Update min line fill interval value 0.05 -> 0.0.1](https://github.com/Snapmaker/Luban/commit/b2dfaf7d9a39f31599b73781e011168091391a50)
- [Fix: SVG file size use original size](https://github.com/Snapmaker/Luban/commit/57a7205ec1751c20d76c31103c72f46e10166f93)
- [Improvement: Modify interlinked parameters for 3D printing support brim](https://github.com/Snapmaker/Luban/pull/2454/commits/4e805cff81f91601daf8f6e9f33252688d600c50)
=> Fix: v4.10.2 part5
